### ISSUE TITLE
[1.10.2] Magenta-Black Textures when installed Malisis Doors & Base Metals

### ISSUE THREAD

**Issue by ghost** [Ordinastie/MalisisDoors#102]
My game is not crashing. but door textures are missing when plaing with MalisisDoors & BaseMetals

**Comment by jriwanek** [comment]
Not a bug in Malisis Doors, This is actually a bug In base metals, I should have it fixed by the next release.

**Comment by 63502** [comment]
Is this no texture bug only a thing with vanilla doors?
Because if so, I think this is happening to me too.
