### ISSUE TITLE
[1.10.2] Crash with Shaders (Optifine C3)

### ISSUE THREAD

**Issue by ruyanve** [Ordinastie/MalisisDoors#107]
Crashing with Optifine C3 on latest MalisisDoors 5.1.2 and Core 4.2.4 on Forge 2095.
Crash happens when a door is placed.
https://gist.github.com/ruyanve/be3c5970de534e967d07c6e589898873

**Comment by Ordinastie** [comment]
This one is all on optifine, I can't do anything for that :s

**Comment by ruyanve** [comment]
Thanks Ordinastie! 
Rolling back to malisisdoors 5.0.4 / malisiscore 4.1.1 fixed the crash on Optifine C4 pre.
The crash got reported to Optifine as well, let's see what comes out of it.

That's still one of the major pains in the behind! I wish someone could come up with open source shader support for minecraft. After playing with shaders for a while it's so hard to go back :-(
