### ISSUE TITLE
[1.10.2] Client crash after placing medieval door in SMP

### ISSUE THREAD

**Issue by xenoflot** [Ordinastie/MalisisDoors#110]
I placed a medieval door a few days ago, no problem, but removed it. I updated the server yesterday and placed it again just now. Client CTD immediately after placing it. On logging back in, I CTD again with an identical error. Rebooted server at the problem remains.

java.lang.NoSuchMethodError: net.malisis.core.block.IBoundingBox.getRenderingBounds(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;)Lnet/minecraft/util/math/AxisAlignedBB;

http://pastebin.com/BHi0g2rK

malisisdoors-1.10.2-5.1.4
malisiscore-1.10.2-4.2.5

**Comment by Ordinastie** [comment]
Update MalisisCore.

**Comment by xenoflot** [comment]
Fixed, thanks!
