### ISSUE TITLE
MalisisDoors bugs vanilla door rendering

### ISSUE THREAD

**Issue by xenoflot** [Ordinastie/MalisisDoors#111]
Running a custom pack based on FTB Unstable 1.10.

With MalisisDoors in the pack, vanilla doors _functionally_ open and close normally however they don't render the change.

Let me know if you can't reproduce and I'll give a full list of mods.

MC 1.10.2
Forge 2107
MalisisDoors 5.1.4
MalisisCore 4.2.7
Forestry 5.2.6.300

**Comment by Ordinastie** [comment]
Does it happen with only MalisisDoors installed ?

**Comment by xenoflot** [comment]
No. I just stripped out everything but Malisis Doors and it's fine. I then re-added Quark and the problem presents itself, so it's an interaction between Quark and Malisis Doors.

Further testing shows it's something to do with the double-doors code since it doesn't affect single doors.

I'll report this to Quark's git as well since it only affects when _both_ mods are installed.

Quark r1.0-59
Autoreglib 1.0-2

Cheers!

**Comment by xenoflot** [comment]
@Ordinastie Since Vazkii "solved" this problem by disabling double-door functionality completely when Malisis Doors is present, would you please add double-door support for non-vanilla doors to Malisis? Alternatively, add a config option to Malisis to disable its double-door support and I'll see if Vazkii will remove the auto-disable he recently added.

Thanks.
