### ISSUE TITLE
Fence gates can't be moved by pistons

### ISSUE THREAD

**Issue by SirDavidLudwig** [Ordinastie/MalisisDoors#112]
I noticed, when looking at an automatic tree farm, that pistons can't move fence gates with this mod enabled. Not a huge issue, but it should probably be looked into...

**Comment by Ordinastie** [comment]
That's something I can't fix at all. Pistons check if the block has a TileEntity to know if they can push it. Vanilla fence gates don't, but mine do (to store all the data).
