### ISSUE TITLE
Which block texture is used by the medieval/carriage door?

### ISSUE THREAD

**Issue by xenoflot** [Ordinastie/MalisisDoors#113]
Hi,

I made some medieval and carriage doors tonight and have found it impossible to colour-match completely. I've tried making them with stone bricks, andesite bricks, diorite bricks and ExtraBricks' diorite bricks and they're all a little different. Enough that it stands out. Noticeably lighter than Stone bricks and a safe darker than diorite bricks.

We do have Quark and TheOneProbe is reporting the blocks as belonging to Quark. Perhaps Quark adjusts the lightness of the blocks?

Anyway to my question, what block textures do you use for these?

Thanks!

**Comment by Ordinastie** [comment]
The same texture is rendered as for the block used in the recipe. However, the shading applied is not correct. It will be fixed in the next update.
