### ISSUE TITLE
High-Tech door oddity

### ISSUE THREAD

**Issue by brisingraerowing** [Ordinastie/MalisisDoors#115]
I placed a High-Tech door to take a look at it, and when I broke it, a magenta and black version appears in the same spot and can't be broken.

MC 1.10.2
MalisisDoors 5.1.4

[Full Modlist](http://modlister.com/user/BrisingrAerowing)

**Comment by Ordinastie** [comment]
Does it happen with only MalisisDoors installed ? Can you replicate it reliably ? Can you show a screen of the result ?

**Comment by brisingraerowing** [comment]
I'll have to toy with it a bit and see if it is a conflict.

**Comment by brisingraerowing** [comment]
It does not happen with only Malisis Doors. I will start going through my other mods and seeing which one is the issue.

**Comment by brisingraerowing** [comment]
I did notice that relogging did get rid of the bugged thing, so that is a workaround for now.

**Comment by Ordinastie** [comment]
I'd really like to know what mods causes conflicts though, and if it's my fault or not.

**Comment by winsrp** [comment]
I had the same issue while I had only davincis vessels (arquimedes something before), and this, I have already talked to the guy of that mod and he said he checked it, and has not found to be his mod., You could put that one up, and give it a test to see if you can find something up.

**Comment by Ordinastie** [comment]
Davinci's vessels did cause issues, but that was resolved together with one of its maintainers. I don't know if they released a new version since.  As for the current issue, without update, I'm closing it.

**Comment by Ben64** [comment]
I'm having this issue, and relogging does not make it go away...

-edit- It happens with just Malisis Doors, Davinci's vessels, and Moving World (library for Davinci)

**Comment by Crowfooted** [comment]
I am also having this issue on a large custom modpack that does include Malisis Doors and Davinci's Vessels/Moving World. Haven't noticed the bug with any other objects so far but I haven't been playing for long.

[This](https://puu.sh/wbGaQ/548593404f.png) is what it looks like. It remains after a relog, and remains even [when blocks are placed inside it](https://puu.sh/wbGgR/97c496d617.png). Not sure if a server restart would fix it - playing on a dedicated server.

Edit: Server restart also does not fix it. I have a permanent pink door in my world now.
