### ISSUE TITLE
Shift-clicking materials into the Door Factory crashes client

### ISSUE THREAD

**Issue by Discomanco** [Ordinastie/MalisisDoors#116]
When shift-clicking materials into/out of the Door Factory, the client crashes.
Dragging and dropping them works just fine.
This does seem to be a newer bug, as I don't recall this happening before, maybe due to one of our recently added mods (mainly AE2/Advanced Rocketry/Railcraft), but I am not sure.

http://pastebin.com/b9bZqrLy

Minecraft: 1.10.2
MalisisDoors: 5.1.4
MalisisCore: 4.2.7
Forge: 12.18.2.2122

**Comment by Ordinastie** [comment]
Should be fixed in the next update of MalisisCore.
