### ISSUE TITLE
Crash After Using Door Factory

### ISSUE THREAD

**Issue by Whimsyturtle** [Ordinastie/MalisisDoors#117]
After Using the Door Factory, the Game Crashes.

Crash Log:
http://pastebin.com/RZQ5GFgZ

(Submitted on Behalf of Shadow_Fade)

**Comment by Ordinastie** [comment]
Does it happen reliably ? Does it happen with only MalisisDoors installed ?

**Comment by Whimsyturtle** [comment]
It happens 2/3 times in my modpack.

However, when I tried with only MalisisDoors and MalisisCore installed, it does not crash.

**Comment by Ordinastie** [comment]
I just realised, 1.7.10. You should just update.
