### ISSUE TITLE
Enhancement: Forestry Doors?

### ISSUE THREAD

**Issue by kojul** [Ordinastie/MalisisDoors#118]
Is there any plans to support extending the vanilla animation replacement to other modded doors like natura and forestry?

**Comment by Ordinastie** [comment]
Unfortunately, it has to be done by the mods author directly. I can't control their blocks like I do with vanilla doors.

**Comment by ghost** [comment]
@Ordinastie How so? Can’t you just make the door animation work for other doors, too?
