### ISSUE TITLE
[Feature Request] Configurable Custom Door Sizes

### ISSUE THREAD

**Issue by SnowShock35** [Ordinastie/MalisisDoors#12]
Hi,

I would like to make a feature request to possibly see configurable door sizes when making custom doors i.e. height and width adjustable sliders in gui This would be really cool to have and I hope you could find a way to implement it. Will bring some neat and interesting builds and would really help out Thanks for reading.
-Snow

**Comment by Mochnant** [comment]
Hopefully something that could go into a "castle" motif will be in the new bigger doors.  3 high x 2 wide would be ideal.
