### ISSUE TITLE
Server TPS drops to .8 warmroast says net.malisis.core.util.chunkcollision.ChunkCollision.getRayTraceResult()95.48%

### ISSUE THREAD

**Issue by ProsperCraft** [Ordinastie/MalisisDoors#122]
https://gyazo.com/0396db1c875c9a7caa9ee1b5802317e8

malisisdoors-1.7.10-1.13.2
malisiscore-1.7.10-0.14.3

**Comment by Ordinastie** [comment]
Yes, that was fixed for Minecraft versions that are not 3 years old :).
