### ISSUE TITLE
Typing 'malisis' in chat calls the command

### ISSUE THREAD

**Issue by lurr** [Ordinastie/MalisisDoors#124]
How to replicate.
1. Open chat
2. Type anything starting with `malisis`, e.g.
> malisis' doors is a great mod!
3. Message is not sent, rather the command is executed.
**NOTE**: Case-sensitive

**Comment by Ordinastie** [comment]
Unfortunately, there is nothing I can do about that.
Apparently, some time ago, some idiot wanted to have client commands without the slash first, and it somehow was added to Forge. 
You'll have to wait until Forge fixes it itself...
