### ISSUE TITLE
door server crash

### ISSUE THREAD

**Issue by knoxhack** [Ordinastie/MalisisDoors#125]
Modpack: Project Ultimate

Server: MMD Public Server

Related Links:
https://minecraft.curseforge.com/projects/mmd-project-ultimate
https://github.com/MinecraftModDevelopment/Project-Ultimate/issues

Crash Report:
https://gist.github.com/knoxhack/4e96db151f071c83e6cf692de28b149e

**Comment by Ordinastie** [comment]
I'll look into it.

**Comment by Ordinastie** [comment]
Fixed in 1.10.2-5.1.7.

**Comment by lordchubz** [comment]
I'm experiencing a similar issue on version 5.1.7

[crash-2017-01-17_16.15.32-server.txt](https://github.com/Ordinastie/MalisisDoors/files/712351/crash-2017-01-17_16.15.32-server.txt)
