### ISSUE TITLE
Trapdoor Light Rendering Issues

### ISSUE THREAD

**Issue by Nullbyte00** [Ordinastie/MalisisDoors#126]
All of the animated wooden trapdoors appear dark at night even when next to a light source.

Test Environment:
MC 1.10.2 FORGE 12.18.3.2185 MALISISDOORS 5.1.6
Tested with only MalisisDoors & MalisisCore installed.
Only tested in SSP.

**Comment by Ordinastie** [comment]
Fixed in 1.10.2-5.1.7.
