### ISSUE TITLE
door server crash on malsisdoor version 1.10.2-5.1.7

### ISSUE THREAD

**Issue by lordchubz** [Ordinastie/MalisisDoors#127]
My server is continually crashing with this crash report.  It looked similar to one of the closed issues from a day ago.

[crash-2017-01-17_16.15.32-server.txt](https://github.com/Ordinastie/MalisisDoors/files/712357/crash-2017-01-17_16.15.32-server.txt)

----------
a little bit more information after a bit of troubleshooting.
One of my player was using the custom pair of double doors and broke one and placed it down, this is when the server crashed.  Downgrading to malsisdoors 5.1.6 allowed me to actually start the server without removing all the doors, where this "bugged/ghost" door was at only showed the frame of a door, oak wood in color, and I wasn't able to target it in an attempt to break it, in creative or not.  It was only half of the double door also, not the entire door.  If it matters the player was using Immersive Engineering Treated Wood for the doors.

After messing with it for a bit, I upgraded the mod back up to 5.1.7 and was able to go over to the door and target it, therefore breaking it.  I'll let you know if any other issues arise with said area.

-----------

even more troubleshooting, so the issue happened consistently when placing any doors from the door factory, not just in the previous trouble location.  Eventually just downgraded back to 5.1.6, and everything seems to be working like normal.

**Comment by zISKo666** [comment]
Hello,

I have the very same problem.

When braking a working 5.1.6 door in 5.1.7 and replacing it, crashed the server also.

Downgrading to 5.1.6 is working for now.

**Comment by Ordinastie** [comment]
Fixed in 1.10.2-5.1.8.
