### ISSUE TITLE
License query 

### ISSUE THREAD

**Issue by StargateMC** [Ordinastie/MalisisDoors#128]
Hi There

I'm presently Redeveloping the pack for my server and hoping to get your Ok to:

1. Develop a fork of this mod
2. Distribute that modified fork as part of a complete pack only.

I do java coding as a hobby and am not sure of licensing restrictions your mod may have so was hoping you could confirm your ok with this.

Alternatively I'll develop a modified server jar to try and change the behaviour of your mod slightly without requiring client changes, but this is a bit annoying haha.

I make no money whatsoever from my pack, I don't even accept donations  so you haven't got anything to worry about there

Site: stargatemc.com

My end goal is a server package with around 100 mods and plugins that are all designed to work together, not just slot in side by side with weird behaviour occasionally.

**Comment by Ordinastie** [comment]
License is MIT, that means you can do pretty much what you want.
But I'm curious about what changes you want to make.

**Comment by StargateMC** [comment]
Generally it will just be hotfixes to ensure that your doors won't be bypassable, and are recognised by our protection plugins etc.

All work we do will be publically available seeing as your license is MIT :) Thanks!
