### ISSUE TITLE
Crash With OptiFine

### ISSUE THREAD

**Issue by ghost** [Ordinastie/MalisisDoors#129]
[malisis crash.txt](https://github.com/Ordinastie/MalisisDoors/files/743074/malisis.crash.txt)
Game won't start. Please help :(

**Comment by Ordinastie** [comment]
Right, I'll fix that tomorrow. Meanwhile, you'll have to disable Optifine I'm afraid.

**Comment by ghost** [comment]
yeah i did, thank you so much. i will be waiting for your awesome mod.

**Comment by ghost** [comment]
https://github.com/sp614x/optifine/issues/461#issuecomment-276503313
may help you :3

**Comment by Ordinastie** [comment]
Fixed in MalisisCore 1.11.2-5.0.1.
