### ISSUE TITLE
[1.10.2] Server crashing on startup, @SideOnly missing.

### ISSUE THREAD

**Issue by rmnaderdev** [Ordinastie/MalisisDoors#131]
Just updated the "All the Mods" mod pack and my server keeps crashing on startup. I originally posted this issue on the Charset Issues page but was told it was Malisis Doors missing a @SideOnly annotation somewhere.

Crash: http://pastebin.com/PXG0nfHK
Original Issue: https://github.com/CharsetMC/Charset/issues/118

**Comment by Ordinastie** [comment]
Will be fixed in the next update.
