### ISSUE TITLE
MalisisDoors/Core: 1.11.2 optifine conflict

### ISSUE THREAD

**Issue by blackviperr** [Ordinastie/MalisisDoors#132]
http://pastebin.com/z6c73NqE - latest log

Enchanted items/potions have no glint/glow animations
*new issue w/most recent update* - default vanilla fog settings are present even with all optifine / dynamic surroundings settings disabled
 
**Note: these issues do not occur when MD/MC are removed.**
![11](https://cloud.githubusercontent.com/assets/25805653/22998810/7fa577c2-f3a6-11e6-9685-a23695bdec4b.PNG)
![1111](https://cloud.githubusercontent.com/assets/25805653/22998814/85b8e48c-f3a6-11e6-8d9e-228935a34554.PNG)

**Comment by Ordinastie** [comment]
Do they occur with only MalisisDoors installed ?
[Edit : nevermind, I have the issue too. I'll look into it.]

**Comment by blackviperr** [comment]
thank you!!

**Comment by Ordinastie** [comment]
Fixed in latest MalisisCore.
