### ISSUE TITLE
Vanilla Doors Textures are Amazing

### ISSUE THREAD

**Issue by ghost** [Ordinastie/MalisisDoors#133]
what's this xD using Optifine b_8 pre, minecraft 1.11.2, forge 2230, malisis doors 6.1.0 malisis core 5.1.1.
![malisis](https://cloud.githubusercontent.com/assets/24831406/23035788/01f567ea-f489-11e6-9a83-fcd33ad5bda2.PNG)
thanks.

**Comment by Ordinastie** [comment]
Log ?

**Comment by kenijey** [comment]
i will update today.

**Comment by ghost** [comment]
here it is.
[fml-client-latest.txt](https://github.com/Ordinastie/MalisisDoors/files/783097/fml-client-latest.log.txt)

**Comment by Ordinastie** [comment]
I don't see anything wrong in the log. Does it happen with only MalisisDoors installed ?

**Comment by ghost** [comment]
i'm using texture packs. do they effect it? you may try to play my modpack if you wish. Its name is MAGENJI in Technic Launcher.
And no, it is not happening when only malisis doors is installed, it is happened after the latest update of malisis doors and core (5.1.1. and 6.1.0). if it is unsolvable. I will downgrade the version of malisis doors sadly...

**Comment by kenijey** [comment]
it is happened after the latest update of malisis doors and core (5.1.1. and 6.1.0). if it is unsolvable, i will downgrade the version of malisis doors sadly...

**Comment by ghost** [comment]
and ah, iron door is fine. just the other doors are problem.
edit: I deleted **all** my resource packs and shader packs, it's still happening.

**Comment by ghost** [comment]
hey ah, i solved the problem, finally. it happens when i install a resource pack which has a bigger size than 16x16. you can try faithful for example. please fix this issue, thanks.

**Comment by EmanYm** [comment]
This sounds more like a resource texture issue than it does a Malisis issue.  Last I checked, it's up to the resource pack you choose to use to provide textures for vanilla doors.

**Comment by Ordinastie** [comment]
Should be fixed in latest version.
