### ISSUE TITLE
[1.11.2-5.1.1] rendering issue

### ISSUE THREAD

**Issue by kreezxil** [Ordinastie/MalisisDoors#134]
With only the 3 mods

Forestry 1.11.20-5.3.1.37
Malisiscore 1.11.2-5.1.1
Malisisdoors 1.11.2-6.1.0

All

the doors provided by Malisis Doors show the attached texture.

Remove Forestry and the doors render properly.

![2017-02-17_15 08 09](https://cloud.githubusercontent.com/assets/3880072/23083603/1750560e-f524-11e6-810f-012be2c4525a.png)

fml-client-latest.log: https://gist.github.com/kreezxil/a817477852aaf0107d4b0146aade6b3a

issue has also been created with Forestry @ https://github.com/ForestryMC/ForestryMC/issues/1601

**Comment by Terpo** [comment]
just a short reminder here: 
Forge 2296
forestry_1.11.2-5.3.4.99.jar
malisiscore-1.11.2-5.1.1.jar
malisisdoors-1.11.2-6.1.0.jar

![2017-05-11_19 06 59](https://cloud.githubusercontent.com/assets/4256058/25962184/15b80798-367d-11e7-8940-c71ca4775361.png)

Log: https://gist.github.com/Terpo/984e15be8849a5f5ebd71a5f129d3390 (nothing interesting there I think)

**Comment by Ordinastie** [comment]
Should be fixed in latest version.
