### ISSUE TITLE
Hi-Tech door Can

### ISSUE THREAD

**Issue by BossRedRanger** [Ordinastie/MalisisDoors#135]

**Comment by BossRedRanger** [comment]
Placed the Hi-Tech door in world. When broken the door outline remains. Picture: http://i.imgur.com/9zqPGac.png

**Comment by Ordinastie** [comment]
Does it still happen in latest version ?

**Comment by FENG-MASTER** [comment]
yes, it still happen in latest version ,1.10.2

malisisdoors-1.10.2-5.2.0
malisiscore-1.10.2-4.4.0
OptiFine_1.10.2_HD_U_E7

**Comment by Ordinastie** [comment]
Except, that's not latest version. That's not even latest Minecraft version. That issue was fixed in 1.11 if I recall correctly.
