### ISSUE TITLE
[1.10.2] ExceptionInInitializerError with Malisis Doors trying to load a Client instance

### ISSUE THREAD

**Issue by Morpheus1101** [Ordinastie/MalisisDoors#139]
Crash report @ https://puu.sh/v1d3I/60e6d132f9.txt

M.Core v4.4.0
M.Doors v5.2.0
Forge *.2254

**Comment by Ordinastie** [comment]
You need to update Optifine.

**Comment by Morpheus1101** [comment]
My apologies, if id realised Optifine was in the pack i wouldnt have bothered reporting the issue, my bad on that one.
