### ISSUE TITLE
Doors return an immutable collection for their drops

### ISSUE THREAD

**Issue by exaskye** [Ordinastie/MalisisDoors#140]
https://github.com/Ordinastie/MalisisDoors/blob/e59d8dfbe6fdf89401f281d5f903db4b16559806/src/main/java/net/malisis/doors/block/Door.java#L332

All vanilla code and most mod code returns modifiable ArrayLists for drops, and a number of mods (including my own) expect this, and call List::remove or List::clear in HarvestDropsEvent.

Please return an empty ArrayList to keep with vanilla behavior.

**Comment by Ordinastie** [comment]
Will be fixed in the next update.
