### ISSUE TITLE
[1.11.2-6.1.0] No recipes for medieval or carriage door

### ISSUE THREAD

**Issue by Aphyxia** [Ordinastie/MalisisDoors#145]
I know the patchnotes said it fixed the recipes but JEI gives me nothing.

Tested with forge 2266 without other mods and 2282 with other mods.
Malisiscore 5.1.1

**Comment by Ordinastie** [comment]
It's a special recipe so it won't show in JEI. But it should still work in a crafting table.

**Comment by Aphyxia** [comment]
Oh, okay. 
The forum description is very confusing however. kept trying to craft it using 1+5 doors but it was instead 1 door + 5 planks.
> A big and fancy wooden double door (4x5x1 multi-block) made from a wooden door and five of one other. Oak door makes a Carriage door, Spruce Door makes a Medieval door. The frame uses the texture of the block used in the recipe.
