### ISSUE TITLE
double doors dont open properly anymore after updating another mod

### ISSUE THREAD

**Issue by hunnybunny21** [Ordinastie/MalisisDoors#146]
double doors dont open properly anymore after updating another mod
and other door glitches 

not sure which mod
i suspect quarks mod

random things is another updated mod
storage drawers

**Comment by hunnybunny21** [comment]
StorageDrawers-1.11.2-4.2.2
RandomThings-MC1.11.2-3.8.1
Quark-r1.2-90
malisiscore-1.11.2-5.1.1
malisisdoors-1.11.2-6.1.0

**Comment by hunnybunny21** [comment]
https://youtu.be/h0GQsum6zj8

**Comment by Ordinastie** [comment]
There should be a config in Quark to disable double door interaction.
