### ISSUE TITLE
Custom Pack loads everything then shuts down with Malasis Doors installed.

### ISSUE THREAD

**Issue by NiteHunter** [Ordinastie/MalisisDoors#148]
I love the mod, too much to not include it. But it's not playing well currently.

V: 1.10.2
Forge: 1.10.2 - 12.18.3.2185

I have the same version (and Mal-core version) installed on another instance and they work great, so I don't know what I broke when I added about 40 other mods to this pack. The error code is only showing this as the issue though, and removing the doors mod allows everything to run again.

Attached error log.

Cheers,
Nate
[crash-2017-04-25_12.54.59-client.txt](https://github.com/Ordinastie/MalisisDoors/files/955886/crash-2017-04-25_12.54.59-client.txt)

**Comment by Ordinastie** [comment]
Update Optifine.
