### ISSUE TITLE
Rusty Hatch turns into single blocks - DUPE BUG

### ISSUE THREAD

**Issue by hanakocz** [Ordinastie/MalisisDoors#150]
Hi there,
got this problem now twice after server restart.
I had those fancy doors, Rusty Hatch...it is multiblock, and everything works perfectly....until that restart of server. Then it behaves as 12 single blocks not interacting with each other, it cannot be interacted with etc...so I went to break it and replace again, but then every of those blocks dropped itself, so I ended up with 12 rusty hatch items, instead of 1.

Also this rusty hatch sometimes don't render the frame and ladder...but it still works..

EDIT: even though I replace it, my co-player sees it as broken/solid blocks/not working

**Comment by Lothrazar** [comment]
Did this ever get fixed?

**Comment by Ordinastie** [comment]
Should be fixed (finally) is 1.12.2-7.1.1.
