### ISSUE TITLE
Random Hi-Tech Doors on the moon bug

### ISSUE THREAD

**Issue by darthvader45** [Ordinastie/MalisisDoors#151]
From jjjworley on the MCF topic:

This is a strange one. I am using 1.11.2-6.1.0, and Galacticraft 4. As soon as I went to the moon, 3 high tech doors appeared hovering in mid air. They are in the same positions as on the overworld.

When I came back to the overworld, the 3 high tech doors were invisible. They still work, just can't see them.
![Bug pic 1](http://media-minecraftforum.cursecdn.com/attachments/253/507/636304952633969488.png)
![Bug pic 2](http://media-minecraftforum.cursecdn.com/attachments/253/508/636304953488312698.png)

**Comment by Ordinastie** [comment]
Fixed in latest version.
