### ISSUE TITLE
Reinforced world generated door turns into door that crashes server for ever.

### ISSUE THREAD

**Issue by frenchiveruti** [Ordinastie/MalisisDoors#153]
https://paste.ee/p/Shz2E
It's a render/drop table issue.
Greets

**Comment by Ordinastie** [comment]
Paste seems to have expired.

**Comment by frenchiveruti** [comment]
Welp... I don't think I have that report anywhere around, this is because I trusted MultiMC auto posting method...
The steps to reproduce are to take a door from a world gen structure (I think it's a warehouse with lots of buttons) and by some random chance I got a door that broke the server, and crashed on load.

**Comment by Ordinastie** [comment]
Open new issue if crash happen again.
