### ISSUE TITLE
Important Textures BUG

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [Ordinastie/MalisisDoors#154]
This BUG with soartex pack and some model texturespack
it looks like this
![2017-05-06_10 39 00](https://cloud.githubusercontent.com/assets/20567492/26274006/967ec458-3d70-11e7-950b-72bf4b5ee796.png)
on soartex forums
![uc 20170520152607](https://cloud.githubusercontent.com/assets/20567492/26274016/d11bb0c6-3d70-11e7-8381-ebf83d0f9025.png)
link:http://forums.soartex.net/threads/1-10-2-vanilla-door-texture-conflict.1721/

**Comment by EmanYm** [comment]
I still don't understand why a texture pack is blaming a mod for broken textures.  From the little bit I used Malisis Doors so far, it doesn't bother the vanilla textures.
*shrug* I could be mistaken, let's see what Ordinastie has to say.

**Comment by mgdgfbhevdyeh** [comment]
But soartex textures pack a lot of players use.
also
This BUG does not happen only on soartex
Many model textures pack will have the same problem

**Comment by Ordinastie** [comment]
Main problem is, I still can't replicate the issue... If I can't replicate, I can't fix :/

**Comment by mgdgfbhevdyeh** [comment]
First download the soartex pack,Next install MalisisDoors
and launch Game

**Comment by Ordinastie** [comment]
Out of curiousity, which one of these three steps do you think I missed ?

**Comment by mgdgfbhevdyeh** [comment]
hmm... ...looks it's work in new MalisisDoors(or it's Optifine things?)
But the side of the door will is vanilla textures
![2017-05-28_21 14 38](https://cloud.githubusercontent.com/assets/20567492/26529057/4f8f85d8-43eb-11e7-8e20-dbf97f54e9a4.png)

**Comment by mgdgfbhevdyeh** [comment]
@Ordinastie Soartex/Issues#10
I have also met（in FTB Beyond）

**Comment by Ordinastie** [comment]
Reopen if it still happens in latest version.

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
in my case (1.12),
the wooden doors (except oak)
are just fine,
iron is completely missing
and oak side and bottom looks like vanilla but faces are missing
