### ISSUE TITLE
Texture bug, without resource pack

### ISSUE THREAD

**Issue by NicosaurusRex99** [Ordinastie/MalisisDoors#155]
Issue,
all doors show alot of textures on the top section rather than the top section of the door

Versions
Minecraft: 1.11.2
Forge: 13.20.0.2304
MalisisCore: 5.1.1
MalisisDoors: Boo 6.1.0

Link to video
https://youtu.be/QucAFkCrhNs

**Comment by TheLimePixel** [comment]
This bug has been going on for 2 months now. I'd greatly appreciate it if it's fixed.

**Comment by Ordinastie** [comment]
Most likely a duplicate of #154 .

**Comment by NicosaurusRex99** [comment]
@Ordinastie there was no resource pack involved though

**Comment by FiveEYZ** [comment]
setting `B:config.modifyVanillaDoors=` to false fixes this

bye bye animated vanilla doors

**Comment by NicosaurusRex99** [comment]
y no mid point, keep animation remove buggy texture @FiveEYZ
