### ISSUE TITLE
Door animations not always present

### ISSUE THREAD

**Issue by BaccarWozat** [Ordinastie/MalisisDoors#158]
In worlds where the terrain is taller than 256 blocks (such as [Cubic Chunks](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2792887-cubic-chunks-mod-almost-infinite-world-height-and) ), though the doors open and close they lose their animations. Tested at Y>2048. The jail door still animates though.

Using Forge 2311, MalisisDoors 6.1.1, MalisisCore 5.2.0 and Cubic Chunks 0.0.615.0.
In all honesty, though, I don't need the animations to work; I just wanted to report the behavior.

![2017-06-09_00 14 28](https://user-images.githubusercontent.com/8357501/26962105-85f6a28e-4ca9-11e7-9665-b4755c9eeb73.png)

**Comment by EmanYm** [comment]
Doors don't animate at normal elevations, either.  They appear invisible at first, and clicking them does not show them as open either.
This might be a Sponge incompatibility, though, so I'm not going to demand a fix for an api that's not officially supported by this mod.

**Comment by Terpo** [comment]
I don't think thats a sponge issue. We have also issues in our modpack, especially with double doors. With a sneak rightclick both open. With normal rightclick only one opens. Sometimes they are out of sync so you can walk through closed doors or can't walk through when open. Elevation level does not matter.
1.11.2
forge 2315
malisiscore-1.11.2-5.2.1
malisisdoors-1.11.2-6.1.1
and quark:  Quark-r1.2-93 (door mechanics should be disabled)
http://blog.terpo.org/upload/mc/modlist.txt

**Comment by Ordinastie** [comment]
No, it's a kind of a Cubic Chunk issue. The regular way of transmitting of a block position via network can't work with Cubic Chunk. The fix would require to rewrite all the packets to allow wider Y values. Probably not gonna happen anytime soon, sorry.

**Comment by Terpo** [comment]
For my problem, we don't use Cubic Chunk. Should I open a new issue?

**Comment by Ordinastie** [comment]
The issue is most likely the same. The coordinates for the positions are packed in way that the Y value is limited. If the Y value is to high (or below 0), the data is lost.

**Comment by Terpo** [comment]
My doors are placed on Y 67.

**Comment by Ordinastie** [comment]
Check if it happens with only MalisisDoors installed.

**Comment by Terpo** [comment]
Found the issue. Its a quark <-> malisisdoors compat issue
I could fix it by changning the config of quark:
    B:"Double doors open together"=false
