### ISSUE TITLE
Hi-Tech Door breaking light rendering when HUD is toggled OFF

### ISSUE THREAD

**Issue by Revvilo** [Ordinastie/MalisisDoors#159]
Only seems to affect solid blocks, except for grass, probably because it has a more specific render to it.
- MC • 1.10.2
- Forge • 12.18.3.2316
- Malisis Doors • 5.2.0
- Malisis Core • 4.4.0

With Door:
<img src="http://i.imgur.com/7eBUHiv.png" width="500">
Without Door:
<img src="http://i.imgur.com/jatQBS1.png" width="500"/>
Bonus; affects night time lighting as well.
<img src="http://i.imgur.com/OCLDRJ4.png" width="500"/>

**Comment by NicholasFeldman** [comment]
This also adds a weird glow to items held in the hand in first person.

**Comment by Ordinastie** [comment]
Will be fixed in the next update.
