### ISSUE TITLE
Texture error? crashes game when used with Integrated Dynamics suite (Cyclopscore)

### ISSUE THREAD

**Issue by sharkck** [Ordinastie/MalisisDoors#160]
It appears there's a texture-related bug that is causing a crash.  Here is the logfile:

[crash-2017-07-15_15.51.02-client.txt](https://github.com/Ordinastie/MalisisDoors/files/1150597/crash-2017-07-15_15.51.02-client.txt)

Hope this helps!

**Comment by zISKo666** [comment]
same crash here ...

**Comment by Ordinastie** [comment]
Can you check if it still happens with those builds ?
MalisisCore : https://puu.sh/wKrNI.jar
MalisisDoors : https://puu.sh/wKrPy.jar

**Comment by sharkck** [comment]
Got this
[crash-2017-07-15_16.32.48-client.txt](https://github.com/Ordinastie/MalisisDoors/files/1150606/crash-2017-07-15_16.32.48-client.txt)

**Comment by Ordinastie** [comment]
Can you confirm it happens on the client ?

**Comment by sharkck** [comment]
That is a client crash log.  It happens on the first loading step when you launch the client.

**Comment by Ordinastie** [comment]
For some reason, the game can't find the class PngSizeInfo, I have no idea why...
And it doesn't happen in dev either...

**Comment by sharkck** [comment]
[crash-2017-07-15_16.46.17-client.txt](https://github.com/Ordinastie/MalisisDoors/files/1150611/crash-2017-07-15_16.46.17-client.txt)

I have bumped it down to just these mods:
![screenshot 2017-07-15 16 52 18](https://user-images.githubusercontent.com/960552/28242604-fece215a-697d-11e7-867c-7673ebc4c62c.png)
![screenshot 2017-07-15 16 54 08](https://user-images.githubusercontent.com/960552/28242614-3c9d0b5e-697e-11e7-9c78-3ef5d7b2e6c4.png)

I'm using OpenEye so a detailed break down of everything plus some more info is uploaded automatically to there.  The most recent ones with just the affected mods dont seem to be showing up on the OpenEye site yet (I guess they're processing).
http://openeye.openmods.info/crashes/5a7096f3cbd10edfe174976f13be37cc

http://openeye.openmods.info/crashes

Here's the openeye files for the pending reports that I have in my folder:
[Pending Crashes.zip](https://github.com/Ordinastie/MalisisDoors/files/1150614/Pending.Crashes.zip)

**Comment by Ordinastie** [comment]
Don't bother, the crash happen with only Malisis mods installed.
I kinda figured out what the problem is, but I have no clue how to fix it...

**Comment by sharkck** [comment]
Care to elaborate?  Maybe some of the others looking at this can assist?

**Comment by Ordinastie** [comment]
Basically, I can't let the ASM library recompute the stack frames as it fails to infer the common super class, I have to include them manually.
Or at least, that my understanding of the issue.

**Comment by Niko-sk2x** [comment]
You could also maybe create your own classwriter that has hardcoded common superclasses for the classes it fails with. *Maybe* it would work. I've never tried it.

**Comment by Ordinastie** [comment]
Fixed.
