### ISSUE TITLE
 [1.12] Missing Texture if B:config.modifyVanillaDoors=true on dedicated server

### ISSUE THREAD

**Issue by Fundryi** [Ordinastie/MalisisDoors#162]
If it is B:config.modifyVanillaDoors=false textures work just fine.
[Image](https://i.imgur.com/RqxWVgS.jpg) Every Vannila door.

**Comment by Ordinastie** [comment]
That doesn't look like doors at all.
Does it happen with only MalisisDoors installed ?
Do you have resource packs installed ?

**Comment by Fundryi** [comment]
It only happens when MalisisDoors is installed.

**Comment by Ordinastie** [comment]
That's not what I asked.

**Comment by trilexcom** [comment]
hi Ordinnastie we are having the same issue when MalisisDoors are instaleld and i am using Vanilla texture pack, Forge version : 2420 MalsisDoor Version number : 1.12-7.0.2 here is a screenshot http://imgur.com/ZHGYhr5

**Comment by redo6565** [comment]
having same issue with malisis dorrs installed and no resource packs

**Comment by CmdrFluffy** [comment]
Having same issue, I went through and removed all other mods, as I had a conflict with Optifine and Tinker's contruct, but this only seems to happen when Malisis doors is active

**Comment by Ordinastie** [comment]
So, the critical information that nobody mentioned : it only happens when connecting to a server.
It's actually an issue with Forge, and until it's fixed you'll have to disable modifyVanillaDoors when playing on dedicated servers.
