### ISSUE TITLE
[1.12] Sponge Incompatibility

### ISSUE THREAD

**Issue by tgstyle** [Ordinastie/MalisisDoors#163]
Crash log here
https://gist.github.com/tgstyle/471e457d5514bbb938e84ec559e5da6f

**Comment by Ordinastie** [comment]
What makes you think it's MalisisDoors ?

**Comment by tgstyle** [comment]
MalisisDoors causes the crash when in the mods folder? It works without sponge.

**Comment by tgstyle** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1678

**Comment by tgstyle** [comment]
If not there is now an issue open with sponge.

**Comment by Ordinastie** [comment]
You should post the full log.

**Comment by tgstyle** [comment]
Full crash log
https://gist.github.com/tgstyle/acb1ea68c6cd85a57f422d70735b4acc

**Comment by tgstyle** [comment]
Full server log
https://gist.github.com/tgstyle/6abd7a3bfd0911dc359f69a92ef74c05

**Comment by tgstyle** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1672

**Comment by tgstyle** [comment]
In 1672 TekuSP mentioned -
"Okay, Looks like MalisisDoor is for unknown reasons registering vanilla minecraft doors as doors without name, texture and that small texture. I recommend catching this issue in Sponge, but looks like bug of MalisisDoors."

**Comment by Ordinastie** [comment]
Should be fixed in the latest update.

**Comment by tgstyle** [comment]
Unfortunately I am seeing the same error.
