### ISSUE TITLE
[1.12] Random crash

### ISSUE THREAD

**Issue by angelnc1989** [Ordinastie/MalisisDoors#166]
Minecraft 1.12
Forge 14.21.1.2443
MalisisDoors 7.0.4
Malisis Core 6.0.3

[Crash log](https://pastebin.com/G7ntfhMS)

I can't really tell you what happened, the game crashed while I was afk, so there was no player interaction.

**Comment by Ordinastie** [comment]
Fixed in MalisisDoors 1.12.2-7.2.0
