### ISSUE TITLE
Strange rendering issue with carriage doors

### ISSUE THREAD

**Issue by andrewminer** [Ordinastie/MalisisDoors#169]
I've used carriage doors on a number of occasions, but this is the first time I've run into anything like this.  To put it briefly, I'm seeing some "phantom" blocks being rendered when I place a carriage door near a certain position in my world.  Let me describe with some images.

First, here's the area which receives the "phantom" blocks once the door is placed.  I've cleared out all the surrounding blocks to make it more clear exactly what is going on.  My character is facing southeast, so you can see, that is at the southeast corner of a chunk.

![2017-08-06_23 42 31](https://user-images.githubusercontent.com/445000/29015405-c0c8a07e-7b02-11e7-8ab0-4c0343a665d2.png)

Now, I move north along the chunk border to where I ultimately want to place the door.  As you can see, the place where the door is to be located is situated exactly along the same N-S chunk boundary, and is divided across the boundary between the affected chunk and the one directly to the north of it.

![2017-08-06_23 42 45](https://user-images.githubusercontent.com/445000/29015481-0537226c-7b03-11e7-8089-907f9abf1c83.png)

Next, I place the door in the opening.  In order to place the door, I walked out into the courtyard and placed it on the left-most block of the opening (the right-most in this image, which is taken from the opposite direction).  In this orientation, the door will open towards me.

![2017-08-06_23 43 05](https://user-images.githubusercontent.com/445000/29015562-50bd0b02-7b03-11e7-84e5-124278483461.png)

However, if I walk back over to the other end of the chunk, I now see some "phantom" bricks floating in the hole!

![2017-08-06_23 43 16](https://user-images.githubusercontent.com/445000/29015619-9c862884-7b03-11e7-8d2a-bf0f25c8c311.png)

These bricks don't actually exist, and nothing I do can get rid of them.  Here's a list of things I've tried:

* filling them in with regular blocks and breaking them
* filling them in with glowstone / torches and breaking them
* filling them in with water, filling that with sand, and then removing all the sand
* using MCEdit to look for blocks in that location (there were none)
* using MCEdit to fill the area and removing the blocks in game

Furthermore, though it's impossible to see, this isn't the entire affected area.  There are several blocks above these which are locked into the "air" texture.  That is, no matter what block is placed in that position, they simply won't render anything at all.

To further demonstrate the non-existence of the blocks, here's a view with the debug console turned on.  If they were real blocks, of course, you'd expect their block data to appear in the lower-right chunk of text.

![2017-08-06_23 43 42](https://user-images.githubusercontent.com/445000/29015762-38d17fcc-7b04-11e7-8fa6-f8bf01de399c.png)

It turns out, if I place the door with the same orientation, but 1m further to the west, the "phantom blocks move as well.  Here's the new door position:

![2017-08-06_23 44 08](https://user-images.githubusercontent.com/445000/29015792-54d9c986-7b04-11e7-840e-544472fd98f0.png)

And the corresponding change in the "phantom" blocks:

![2017-08-06_23 44 27](https://user-images.githubusercontent.com/445000/29015804-62e993da-7b04-11e7-8708-d52a6e02ad33.png)

Here are a few things I've found which fixes it:

* removing the door instantly removes the "phantom" blocks
* place the door further away from the corner of the chunk
* turn the door around (i.e., so it opens into the courtyard instead of the hall)

I am using the following versions:

* Minecraft 1.10.2
* Forge 12.18.3.2239
* MalisisCore 4.4.0
* MalisisDoors 5.2.0
* Optifine HD U D8

In fact, the whole modpack is available on Github at: [andrewminer/quiet-countryside](http://github.com/andrewminer/quiet-countryside).

I would be very grateful if you could look into the problem!  Thanks!

**Comment by Ordinastie** [comment]
Can you replicate with only MalisisDoors installed ?
Also, can you check if it happens when placing a chest in the chunk ?

**Comment by andrewminer** [comment]
> Can you replicate with only MalisisDoors installed ?

No, I'm afraid not.  I created a new modpack with just the Malisis mods installed (core/doors/switches), and nothing I did was able to reproduce the problem.  I even tried pulling in various other mods which I thought may be related (due to the proximity of blocks from those mods), but to no effect.  These were:

* Underground Biomes Constructs
* Chisel 2
* Chisels & Bits
* Optifine

I also noticed a few other odd symptoms in the world which is experiencing the issue:

* the hit target for the door seems to only include the block where the door was actually placed
* the Hi-Tech Door, when broken, leaves behind a purple & black version of itself.  This cannot be removed by any means (replacing the door, placing other blocks, placing the door and breaking it again, breaking the door open/closed, using MCEdit to remove it), but it doesn't block the player.  In the end, nothing I did was able to remove the phantom door, and I needed to restore the world from a backup.

> Also, can you check if it happens when placing a chest in the chunk ?

The chest seems to work normally, and nothing odd happens.

----

In any case, I'm pretty well convinced the issue has to be some kind of bizarre interaction between MalisisDoors and some other mod, but with over 100 in the modpack, it's pretty hard to tell which.  😢 

If you're interested in investigating further, I can send you a Dropbox link to a recent backup of the server (which will have the mods, configs, and map data).  However, I can certainly understand if you're not keen on trying to figure this out with so little to go on.

**Comment by Ordinastie** [comment]
I just noticed you were playing in 1.10.2. Most of the things you mentioned have been fixed in later versions.

**Comment by andrewminer** [comment]
Ah, I see.  Any chance of those fixes getting back-ported to the 1.10.2 version?  I ask because this is a substantial modpack where many of any important mods aren't available for anything more recent than 1.10.2...

**Comment by Ordinastie** [comment]
Unfortunately, no, I only maintain 2 versions for each mod.

**Comment by andrewminer** [comment]
Understandable, but sad.  I think I'll have to pull the mod from the modpack, in that case.  The Carriage Door thing we could work around, but I just can't have someone placing a Hi-Tech door down in the world and needing to restore a backup for the whole server to get rid of it.  💣

**Comment by Ordinastie** [comment]
The Hi-Tech door is just a visual glitch. Reloading the game should get rid of it.

**Comment by andrewminer** [comment]
That wasn't my experience.  I restarted both client and server, and the problem didn't resolve.  More and more, I'm thinking that Optifine may be the culprit.  I have another player on the server who says that all of the UBC stone is showing as plain black blocks.  As you can imagine, this makes going down into caves pretty much impossible for him.  However, it also sounds like a funny visual glitch with texture finding, much like this bug, and similar to the issue with the Hi-Tech Door.  I'll experiment with removing that to see what happens.
