### ISSUE TITLE
1.12 vanilla doors missing textures error

### ISSUE THREAD

**Issue by tiarnia** [Ordinastie/MalisisDoors#172]
all my vanilla style doors are pink and black squares 
1.12-7.0.4
core is 6.0.3

**Comment by bloodmc** [comment]
@Ordinastie I can confirm this issue with latest build.

**Comment by Ordinastie** [comment]
Are you using LiteLoader ?

**Comment by bloodmc** [comment]
Yes

**Comment by Ordinastie** [comment]
Will be fixed in the next update.
