### ISSUE TITLE
Player Sensor Doesn't work with Hi-Tech Door

### ISSUE THREAD

**Issue by tankcr** [Ordinastie/MalisisDoors#174]
It would appear that the player sensor does not work with the Hi-Tech Doors in 1.10.2

**Comment by Ordinastie** [comment]
It's because only the bottom middle block can react to redstone. One way around is to use a Relay for MalisisSwitches.

**Comment by tankcr** [comment]
So then you would put the sensor above the door then a relay in front of the door on the center square?
