### ISSUE TITLE
1.12.1 server crash

### ISSUE THREAD

**Issue by HempNight** [Ordinastie/MalisisDoors#176]
1.12.1 server crashing on start up
using Malisis core doors and blocks
upadted to latest
forge:14.22.0.2467
mc: 1.12 .1

https://drive.google.com/open?id=0B122WqBnrwe7RzZpWGVOTXNvVjg

**Comment by HempNight** [comment]
Update sever will start up with only malisis core if i add door and/or blocks it will crash

**Comment by Ordinastie** [comment]
It's a known compatibility issue with Crafttweaker. It's already fixed for the next update but I've still work to do before release. Hopefully, I'll be able to release it soon.

**Comment by HempNight** [comment]
awsome thanks
