### ISSUE TITLE
Suggestion - ability to combine player sensor with doors via door factory or crafting table.

### ISSUE THREAD

**Issue by alexw235** [Ordinastie/MalisisDoors#177]
Add the ability to combine the player sensor with doors via the mods door factory or via a crafting table.  It would give the whole ensemble a cleaner look (no black bars stuck above every door), and makes your mod work better with the chisel and bits mod which I use to craft walls (the mod alters block states and whether they count as whole blocks so things like your player sensor are hard to attach).

**Comment by Ordinastie** [comment]
I kinda like the idea. I wonder why I didn't think about that sooner.

**Comment by alexw235** [comment]
I just installed the update.  Could you please add to the door factory the ability for doors to close as well, after you've moved a certain distance away?

**Comment by Ordinastie** [comment]
I answered on the MCF thread. Use the auto-close function.
