### ISSUE TITLE
[1.12.2] No sound from Hi-tech door if opened with redstone

### ISSUE THREAD

**Issue by xkobalx** [Ordinastie/MalisisDoors#179]
Issue only seems to affect Hi-tech doors. The door plays its opening sound if opened by right-clicking but not if opened using any redstone source. Tested button, lever etc. Tested other doors just to be thorough.

MC 1.12.2
Forge 14.23.0.2495
MalisisCore 1.12.2-6.1.6
MalisisDoors 1.12.2-7.1.0

**Comment by Ordinastie** [comment]
Fixed in 1.12.2-7.1.1
