### ISSUE TITLE
Malisis doors/SecretRoomsMod compatibility needs to be updated

### ISSUE THREAD

**Issue by mattymaats** [Ordinastie/MalisisDoors#18]
Hi Ordinastie,

First of all just wanted to say thank you for such a great mod, you have no idea how much I like your mod as it actually adds in such a great feature I've wanted for ages. Anyway getting to the point I tried to add SecretRoomsMod to our modpack today and I received the following error.

http://pastebin.com/awKmuGkC

Due to the following being out of date with all the new items you've added in.

https://github.com/AbrarSyed/SecretRoomsMod-forge/blob/master/src/main/java/com/github/abrarsyed/secretroomsmod/malisisdoors/CamoDoor.java

I'm using the following versions just for reference on single player to test.

malisiscore-1.7.10-0.10.3
malisisdoors-1.7.10-1.3.2
secretroomsmod-1.7.10-4.7.1.377
Forge 10.13.2.1236

**Comment by mentimjojo** [comment]
I have to same problem

**Comment by Ordinastie** [comment]
The PR is already done, only thing left is for Abrar to release.
