### ISSUE TITLE
Default doors 1.12.1

### ISSUE THREAD

**Issue by Callum-Bell** [Ordinastie/MalisisDoors#180]
The doors have the black and purple texture on all vanilla doors, except the trap doors, (including iron door). I think its trying to replace my texture pack as when i remove it the doors are still bugged but alittle better, and if i turn on shaders and my texturepack the doors are back to its normal texture

**Comment by Ordinastie** [comment]
You're not specifying neither the MalisisCore nor the MalisisDoors version you're using.
Make sure you installed latest version available.

**Comment by Callum-Bell** [comment]
malisisdoors-1.12-7.0.4
malisiscore-1.12-6.0.4
Both latest

Its random, sometimes textures are fine, i think its when someone interacts with the Door Factory, but thats just a guess

**Comment by Ordinastie** [comment]
It's not latest, please use MalisisCore 1.12.2-6.1.6 and MalisisDoors 1.12.2-7.1.0.

**Comment by Tokeli** [comment]
On Curseforge, you've specified MalisisCore 1.12.2-6.1.6 for 1.12.2 only, and MalisisDoors 1.12.2-7.1.0 for 1.12, so everyone on the lower versions is getting them mismatched by default.

**Comment by Ordinastie** [comment]
The version marked on Curseforge doesn't matter, they still work for both versions.
I have updated MalisisDoors version category anyway.

**Comment by Callum-Bell** [comment]
Yeah i just got confused when it said "1.12.2" i didnt know that works with 1.12.1

**Comment by Tokeli** [comment]
It matters insofar as those not on 1.12.2 using the Curse launcher won't see an update for the mod, that's all!
