### ISSUE TITLE
Door sensing bug

### ISSUE THREAD

**Issue by alexw235** [Ordinastie/MalisisDoors#181]
I've noticed a bug with the player sensing ability of doors created via the door factory where the door doesn't sense the player.  But it only happens if the door is placed facing a certain direction and only from one face of the door.

It's a little hard to describe but to see what I mean, create a 3x3 block hollow cuboid with doors in the center of each face then approach all the doors from the outside.   One of those doors won't sense you when approached.

**Comment by MokahTGS** [comment]
I found this is an issue when these sorts of doors are placed on the east edge of a block.  I'm testing this with the 1.12.1 version in 1.12.2.  A player sensor will "fix" this issue.

**Comment by alexw235** [comment]
Yup, that's it.

Unfortunately my walls are half blocks made via the chisel and bits mod, and since they are not full blocks the player sensor won't attach to it.

**Comment by Ordinastie** [comment]
Fixed in 1.12.2-7.1.1.
