### ISSUE TITLE
Ghost Door.

### ISSUE THREAD

**Issue by Daihok41** [Ordinastie/MalisisDoors#182]
This is a ghost door i can walk straight through doesnt show up in one probe. I cant target or break it. I cant do anything with it. Here is screen.
https://imgur.com/1DlnPQA

**Comment by ghost** [comment]
That resource pack is awful. It looks like Garry’s Mod. Just sayin’.

**Comment by Ordinastie** [comment]
You probably placed a "Double sliding" doors. Try and destroy the block below on the right.
