### ISSUE TITLE
[1.10.2] Graphical Glitch with some doors, more so with Spruce than any other door.

### ISSUE THREAD

**Issue by RepoDraghon** [Ordinastie/MalisisDoors#188]
![javaw 2017-11-15 15-44-43-09](https://user-images.githubusercontent.com/8423696/32864398-3add2c6e-ca1c-11e7-93a4-4dd119b461c6.jpg)

**Comment by Ordinastie** [comment]
FIxed in 1.12-7.0.4.

**Comment by RepoDraghon** [comment]
ah, so you are the type to not fix it for the specific version, just focusing on the latest versions and not looking back... ok, good to know... uninstalling this and mods related... have a nice day...
