### ISSUE TITLE
Incompatibility with Chroma Hills Resource Pack

### ISSUE THREAD

**Issue by ChellieH** [Ordinastie/MalisisDoors#189]
The Chroma Hills pack changes the door models and blockstates to give them a more detailed 3d appearance.

This is what the Chroma Hills doors look like without Malisis Doors installed
![image](https://user-images.githubusercontent.com/10011536/32990743-a849eeb0-cd26-11e7-995c-8e89d14cb99c.png)

This is what the Chroma Hills doors looked like with Malisis Doors installed
![image](https://user-images.githubusercontent.com/10011536/32990747-b2a44810-cd26-11e7-845f-94ff4fec078c.png)

This is what I have managed to accomplish by making an addon to Chroma Hills that rearranged the structure of the resource pack a little. I get the HRes textures but lose the 3d element.
![image](https://user-images.githubusercontent.com/10011536/32990738-9acea140-cd26-11e7-99a4-afc452f19d88.png)

My knowledge of code is pretty limited - is there a way of making the 3d models work with Malisis Doors using resource packs or does the code not support it? I appreciate the work that goes into making mods so if the code does not support it I can make a few tweaks to the textures to account for the lack of 3d elements.

**Comment by Ordinastie** [comment]
Unfortunately no, the code doesn't support models (yet). I plan to rewrite a good part of the mod at some point and model will be supported then.

**Comment by ChellieH** [comment]
Thank you for you swift response and a great mod :)
