### ISSUE TITLE
[1.12.2] Crash when placing fence gate

### ISSUE THREAD

**Issue by LiskoSlayer63** [Ordinastie/MalisisDoors#190]
Firstly, I'm **NOT** sure if this crash is caused by your mod, but Minecraft crashes when placing fence gate (possibly when placing other blocks too) because it "_Cannot get property PropertyDirection as it does not exist in BlockStateContainer_". I uploaded the crash log [here](https://pastebin.com/FnJDGmxH).

**Comment by LiskoSlayer63** [comment]
This might be same problem than [MalisisCore#128](https://github.com/Ordinastie/MalisisCore/issues/128).

**Comment by Ordinastie** [comment]
Fixed in MalisisDoors 1.12.2-7.2.0.
