### ISSUE TITLE
Suggestion: Make hi-tech doors work with player sensor

### ISSUE THREAD

**Issue by StarkRG** [Ordinastie/MalisisDoors#191]
It'd be great if the top blocks of the hi-tech door would respond to redstone so they're compatible with the player sensor from malisis blocks.

**Comment by Ordinastie** [comment]
Only the bottom middle block can react to redstone. I suggest looking at [MalisisSwitches](http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2599581) to acheive what you want.
