### ISSUE TITLE
Malisis doors and Minecolonies

### ISSUE THREAD

**Issue by Raycoms** [Ordinastie/MalisisDoors#193]
I noticed an Issue in 1.12.2 with Malisis doors.

In minecolonies there is a builder which takes a schematic and exactly copies the blockState to another location. This does cause a lot of issues with malisis doors installed like open trapdoors and wrong placed doors.

**Comment by Ordinastie** [comment]
You'll have to be more specific. Your report doesn't contain any information at all.

**Comment by Raycoms** [comment]
It seems like vanilla blockStates don't get converted correctly to malisis block states correctly
