### ISSUE TITLE
[1.12.2] Doors disappear after breaking.

### ISSUE THREAD

**Issue by LiskoSlayer63** [Ordinastie/MalisisDoors#199]
I have your mod on my server and I noticed that if you break a door it disappears instead of dropping. I'm not even sure that this is caused by your mod but every other item/block drops like it should except doors, and your mod is only one which affects doors. I have tested this only for vanilla doors.

**MalisisDoors version:** 7.1.1
**MalisisCore version:** 6.1.7
**Forge version:** 14.23.1.2561
**Minecraft version:** 1.12.2

**Server is also using SpongeForge version:** 2555-7.0.0-BETA-2760

(_I'm not sure how to make a list of used mods with version numbers and everything unless I write the software for that myself. So for now there's only a directory listing for the mods I'm using, if it helps. The list is for client-side mods._)

**Used mods:**
 ```
AdChimneys
AmbientSounds
ArmorsHudRevived
Autofish
BASE
BetterFoliage
BetterFps
BiblioCraft
BirdsNests
Blur
BonsaiTrees
Chameleon
ChestTransporter
ChiselsAndBits
ChunkAnimator
ClientTweaks
Clumps
CraftableHorseArmour
CustomMobSpawner
DeathQuotes
DynamicSurroundings
DynamicTrees
FairyLights
FancyBlockParticles
FastLeafDecay
FenceJumper
FoamFixLawful
ForgeEndertech
FurnitureMod
GraveStone
iChunUtil
ItemPhysicLite
IvToolkit
JustEnoughItems
JustEnoughResources
LunatriusCore
MalisisCore
MalisisDoors
Mantle
MenuMobs
MobDismemberment
MoCreatures
Natura
OpenGlider
OptiFine
PopEnchantTagsRevived
RecurrentComplex
ReptileMod
ResourceLoader
SoundFilters
Stackie
StellarAPI
StellarSky
StorageDrawers
TabbyChat
ToastControl
ToroHealth
TumbleWeed
ViesCraft
VoxelMap
Waystones
WearableBackpacks
WorldClock
```

**Comment by Ordinastie** [comment]
I couldn't replicate on my end. Does it happen if you have only MalisisDoors installed ?

(Note : you can produce a crash report if you press F3+C for a few seconds.)

**Comment by LiskoSlayer63** [comment]
@Ordinastie Thanks for the information! I'll check if there's any conflicting mods when I have enough time, probably report back in couple of days.

**Comment by Ordinastie** [comment]
I found and fixed a bug with item drops that probably resolve this issue with the next update. Please open a new one if it still occurs.
