### ISSUE TITLE
Custom Door Top have no localization, texture

### ISSUE THREAD

**Issue by Adaptivity** [Ordinastie/MalisisDoors#20]
http://i.imgur.com/sX6egGn.jpg Bottom displayed correctly. Is it possible to fix it?

**Comment by Ordinastie** [comment]
Not really. I think it's a Waila issue.

**Comment by Adaptivity** [comment]
https://bitbucket.org/ProfMobius/waila/issue/155/custom-door-top-from-malisis-doors
