### ISSUE TITLE
Game Crash - Trying to get BlockState from BlockAir

### ISSUE THREAD

**Issue by Dockter** [Ordinastie/MalisisDoors#200]
I've also seen this issue prior to the above build number.  MCore: 1.12.2-6.3.0

https://gist.github.com/Dockter/03777d4d21918beac8be8fe0dbef2db9

**Comment by Ordinastie** [comment]
I've had a few reports but I have no clue how that can happen. Tried a way to possibly avoid it. Open another issue if it still happens in MalisisDoors 7.2.1.
