### ISSUE TITLE
Animated blocks (sugestion, please read) ;m;

### ISSUE THREAD

**Issue by SimulatorSia** [Ordinastie/MalisisDoors#201]
For people who don't have a fast computer or don't like an abundance of items they'll never use like a ton of doors, is possible to make a stand alone mod with the vanila block features by theirself like the 1.7.10 Animated Blocks mod?

**Comment by Ordinastie** [comment]
I'm sorry but I don't think I will do that. I may consider a config option to limit the mod to only vanilla modification, but it's not a priority right now.

**Comment by SimulatorSia** [comment]
Alright, thank you though
