### ISSUE TITLE
[1.12.2] Issues with dragging blocks in door factory

### ISSUE THREAD

**Issue by AgentA1cr** [Ordinastie/MalisisDoors#202]
When dragging to distribute blocks in the material slots in the door factory, they behave oddly, deleting or duping blocks.

Mod version: 1.12.2-7.1.3
Forge Version: 14.23.1.2555

**Comment by Ordinastie** [comment]
Can you be more specific ?
Can you replicate it ? What exact actions did you take ? What where the results ?

**Comment by Insane96** [comment]
By right clicking and holding this happens: https://youtu.be/5g_DVrWTIzU
