### ISSUE TITLE
[1.12.2] Double sliding doors not closing correctly or breakable under certain conditions

### ISSUE THREAD

**Issue by AgentA1cr** [Ordinastie/MalisisDoors#203]
I accidentally place a set of double sliding doors with the wrong direction set, and when opened, they slid into the space occupied by another set of similar, already open, doors. After this, I could not close or break the set of misplaced doors by hand. I did not attempt to close them with redstone yet, as my other attempt to break the doors caused the game to crash, as I will detail in a separate bug report.

Mod version: 1.12.2-7.1.3
Forge Version: 14.23.1.2555

**Comment by AgentA1cr** [comment]
Upon reloading the world, it appears that toggling a redstone signal does close the door, allowing it to be broken.

**Comment by Ordinastie** [comment]
Yeah, a double sliding door can render outside of its bounds and not be interactible once opened. Solutions are redstone, placing a corresponding double door, or simly breaking the block it's placed on.
