### ISSUE TITLE
[1.12.2] Open double sliding doors cause crash when moved by piston. 

### ISSUE THREAD

**Issue by AgentA1cr** [Ordinastie/MalisisDoors#204]
Due to the issue cause by #203 I attempted to break the offending doors using a piston. This caused the game to crash. upon reloading the world, the door appears to have been deleted.

Crash Report: https://gist.github.com/AgentA1cr/e38029805abe69f8a221c1b1a88e2bb4

Mod version: 1.12.2-7.1.3
Forge Version: 14.23.1.2555

**Comment by Ordinastie** [comment]
I couldn't replicate but I added a check that should prevent it from happening again.
