### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Nexusdog** [Ordinastie/MalisisDoors#208]
MC/F 1.12.2/2577

https://pastebin.com/WHeThiMF

**Comment by Ordinastie** [comment]
Crash reports are not some mystical encrypted data. They're readable : Caused by: java.lang.OutOfMemoryError: Java heap space
You need to increase the memory given to Minecraft.

**Comment by Nexusdog** [comment]
I have 16G of Ram, the java argument was amended prior to the crash & have 101 mods currently installed all happily chugging away together. I welcome your advice on how to improve my predicament. 

 -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M

**Comment by Ordinastie** [comment]
Note quite : 
Memory: 8952144 bytes (8 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
    JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump **-Xmx1G** -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M

**Comment by Nexusdog** [comment]
I sincerely apologise, I have no idea what's going on then. I copied the latest crash report and java argument, am I missing something?

**Comment by Ordinastie** [comment]
Well, I'm not sure where you copied the arguments from, but the one used by MC uses 1GB instead of the 12 you wanted. (-Xmx1G)

**Comment by Nexusdog** [comment]
I copied the java argument from the launcher/options, modified it to 12G - or at least I thought I had? This is it & I admit I'm finding it harder to grasp what I'm doing wrong.

-Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
