### ISSUE TITLE
[1.12.2] Optifine messes up door textures

### ISSUE THREAD

**Issue by Draskh** [Ordinastie/MalisisDoors#209]
I got missing textures for a door. They appear randomly but most time they are disappeared.
malisisdoors-1.12.2-7.2.2

![2017-12-21_18 52 50](https://user-images.githubusercontent.com/26455012/34335675-e6ad1f24-e950-11e7-81ab-03dfc79b8b50.png)

**Comment by Ordinastie** [comment]
It's something that has been happening for a long time. Some say it's because of Optifine, some claim it happens to them without Optifine. But I could never replicate in dev, so I could never debug it...

**Comment by Draskh** [comment]
I am using Optifine C 7 for 1.12.2 maybe that helps.

**Comment by Ordinastie** [comment]
The question is, does it happen when you remove Optifine ?

**Comment by Draskh** [comment]
without Optifine: 
![2017-12-25_18 52 09](https://user-images.githubusercontent.com/26455012/34342056-24ee2f86-e9a5-11e7-9f21-296f5e4398d9.png)

**Comment by Ordinastie** [comment]
Unfortunately, like I said, I can't really fix if it's an Optifine issue.

**Comment by Draskh** [comment]
Should I report this on the Optifine repo?

**Comment by Ordinastie** [comment]
They won't do anything and most likely shrug it of as "MalisisDoors issue". The main problem is that there is no way to have Optifine inside a dev environment, so no way to actually replicate and debug the problem.

**Comment by Draskh** [comment]
I know what you mean. There are many problems with Optifine. But I do not know why it is still closed source. That's a great mod and causes so many trouble. :/

**Comment by sp614x** [comment]
It looks like the rusty hatch and the frame are rendered separately. One is tile entity and one is block.
When placing the hatch the frame is visible. On subsequent chunk updates the frame disappears. 
This may be the problem: https://github.com/Ordinastie/MalisisDoors/blob/1.12/src/main/java/net/malisis/doors/renderer/RustyHatchRenderer.java#L139

**Comment by Ordinastie** [comment]
Possibly, but without the ability to debug in dev, I can't really say.
The multiblock origin info is stored in a map with Chunk as key. The data is not supposed to be modified and/or removed when a block updates.

Is there really no way to provide a dev env compatible Optifine ?

**Comment by sp614x** [comment]
To get OptiFine in Forge dev env: https://github.com/octarine-noise/simpledeobf/blob/master/README.md#have-optifine-will-debug
by @octarine-noise

**Comment by Niko-sk2x** [comment]
Also note that the suggested way using force public breaks quite a few things and the way around it is to add the forge AT and all your Bf your dependencies ATs into the dev optifine jar instead of using forcePublic
