### ISSUE TITLE
Malisis doors vs. GregTech recipes

### ISSUE THREAD

**Issue by JasonMcRay** [Ordinastie/MalisisDoors#21]
When I have "config.modifyVanillaDoors" config set to true, the recipes in GregTech which uses vanilla doors will become corrupted. Items not craftable. When i set that config to false everything is fixed. Is there anything you can do about this? here is a screenshot of 3 broken recipes using Iron Doors.
![iron door problem](https://cloud.githubusercontent.com/assets/4236895/6204004/fff13224-b53a-11e4-83fc-25b350a96920.png)

**Comment by Ordinastie** [comment]
I would say it's on GT's end. And as he did not make his source available, I can't check and/or debug.
