### ISSUE TITLE
[1.10.2] Texture buggeg through dimmensions

### ISSUE THREAD

**Issue by Steve505** [Ordinastie/MalisisDoors#212]
Hi there!
On our server modpack with Galacticraft, a texture of Hi-Tech Doors placed on Earth is showing on same coordinates in the space around the planet, but only texture. Doors are not there physically. Is there any solution to fix it?

Thanks,
Jason505

![2018-01-03_17 38 26](https://user-images.githubusercontent.com/28407251/34529834-81788c4c-f0ad-11e7-9d0f-00798d320b3a.png)
![2018-01-03_17 40 17](https://user-images.githubusercontent.com/28407251/34529835-819200e6-f0ad-11e7-8e17-4299c1f539d4.png)

**Comment by Ordinastie** [comment]
That was fixed at some point. I don't quite remember when. If you're already using latest version available for 1.10.2, then that means it was fixed in 1.11.

**Comment by Steve505** [comment]
So, you're basically saying that we have to live with this because (for technical reasons) we cannot upgrade whole modpack to 1.11.2? Great.

**Comment by Ordinastie** [comment]
Unfortunately, yes. I can't keep updating older versions. And if I remember correctly, this fix required quite the refactoring so I'm not really willing to backport. Sorry.

**Comment by Steve505** [comment]
Quite stupid, isn't it? Developping mods without releasing a final release with fixed bugs. Another problem with textures in another your mod in our modpack [HERE](https://github.com/Ordinastie/MalisisAdvert/issues/3).
Big disappointment...
