### ISSUE TITLE
Animation of doors opening/closing not working

### ISSUE THREAD

**Issue by GrumpyChunks** [Ordinastie/MalisisDoors#214]
Installed 7.2.3 onto a dedicated forge 2587 server (with 6.3.1 of Malisis Core) on a dedicated server (and client). Server and client also have Quark 1.4-121 installed, along with a small handful of other mods. Quark is configured default with regards to the door behaviour, so should not interfere with Malisis Doors.

When opening doors, there is no animation and a delay of about 1 second before the visual state of the door changes (though the door acts as if it's changed state immediately).

I've reverted back to 7.2.2 and 6.3.0 on both server and client and the problem has gone away.

Also noticed [this exception](https://pastebin.com/jSbFxYTc) in the server log, which occurred 20 mins after the server was started, I'm not sure, but it *might* have been triggered by me placing/using an oak door, though I can't be sure about this.

One other odd thing I've noticed, is that one of three oak doors I crafted, shows as a 'rotating' oak door, and I've no idea why this is. The other two appear normal.

**Comment by kiwifrogg** [comment]
Just to add to this if you power any of the rotating doors(vanilla) the server boots all the players online with an exception. Nothing shows up in the logs

**Comment by Ordinastie** [comment]
@kiwifrogg please open a separate issue. Also, you don't provide any helpful information for me to help you.

**Comment by retsej22** [comment]
Only vanilla doors animation doesnt work. Custom doors animation work.

**Comment by Ordinastie** [comment]
I have started debugging it.

**Comment by Endmateria** [comment]
Yeah, I think the exception @BinaryCrafter mentioned is somehow related to the broken double doors animation (I'm getting the same error).  On my server, I'm sitting here opening and closing my vanilla birch double doors, and every time I open and close them it triggers the same exception in my server log.  I'm using same mod/forge versions as the OP. (Also using Quark, with double door option disabled)

**Comment by Ordinastie** [comment]
So, I was having the issue in dev too, but then it stopped happening... I can't replicate it anymore.
Note that the exception linked is not related and will be fixed in the next update.

**Comment by Ordinastie** [comment]
Please test again with 1.12.2-7.2.4 and tell me if you still have the issue.
Note that I updated to Forge 1.12.2-14.23.1.2589.

**Comment by Endmateria** [comment]
@Ordinastie Did you upload 7.2.4?  I'm not seeing it on Curseforge.

**Comment by Ordinastie** [comment]
Yeah, it's still under review. You'll have to wait until the shift starts at Curseforge.

**Comment by retsej22** [comment]
I tried 1.12.2-7.2.4 with Forge 1.12.2-14.23.1.2589 and i still have this issue. Vanilla door animation doesn't work.

**Comment by Ordinastie** [comment]
Did you update MalisisCore too ?

**Comment by Endmateria** [comment]
I updated both (core and doors) and I'm not getting the animation glitch at the moment.  I'm gonna try restarting the server a couple times though, given that the glitch was inconsistent to begin with.

**Comment by retsej22** [comment]
Yes i uptaded both and i still have this issue.This issue is about only config. @Ordinastie  Sorry about this.

**Comment by Ordinastie** [comment]
Does it happen with only MalisisDoors installed ?

**Comment by kubilayerislik** [comment]
I tried only malisis and quark. it worked. When i tried FTB Revelation animation doesnt work. I think some mods disabled vanilla door animation.

**Comment by Endmateria** [comment]
@kubilayerislki  What's your full mod list look like?

**Comment by Endmateria** [comment]
@kubilayerislik Here's mine.  https://gist.github.com/Endmateria/eca626a04ce0675ce8369032865c430a  I know Foamfix messes with/tweaks animation presets a bit, but that's not on your list.  Architecturecraft's code is a mess right now, but I don't know how much that would influence doors.  I'm going through configs right now, looking for anything that would influence door animations.

**Comment by Ordinastie** [comment]
For those with the issue, you try with this version of MalisisCore : https://oss.sonatype.org/content/repositories/snapshots/net/malisis/malisiscore/1.12.2-6.3.3-SNAPSHOT/malisiscore-1.12.2-6.3.3-20180115.163150-2.jar ?
Then type /malisis debug syncer in chat and post the client and server log output.

**Comment by Endmateria** [comment]
@Ordinastie I personally have not been able to duplicate this problem since you updated your mods to 7.2.4 and 6.3.2, and I've been rebooting the server constantly while messing with other mods.

**Comment by GrumpyChunks** [comment]
Working for me now, having updated both server and client to 6.3.2/7.2.3

**Comment by Ordinastie** [comment]
Please update MalisisDoors to 7.2.4 :)

**Comment by GrumpyChunks** [comment]
Yes, also working fine with 7.2.4. (Didn't see 7.2.4 when I updated a few hours ago). Many thanks!

**Comment by Ordinastie** [comment]
@kubilayerislik You're the last one saying you still have issues. Can you confirm it still happens for you with MalisisCore 6.3.2 and MalisisDoors 7.2.4 on **both client and server** ?

**Comment by retsej22** [comment]
You can close this issue i update 7.2.4 and animations work fine.
