### ISSUE TITLE
[1.12.2]Vanilla doors now named rotating door and boot all players if powered with buttons or plates(server only).

### ISSUE THREAD

**Issue by kiwifrogg** [Ordinastie/MalisisDoors#215]
In the latest version, the vanilla doors are relabelled rotating iron door(for example), if you try to power the doors with a red stone signal the server boots all the online players with a personal error saying A "fatal error has occurred, this connection is terminated". You need to relog and be booted a few times for the door to finish its opening animation then the door(in this case iron) will be stuck open.   Nothing shows in the server logs, the error does show in the game log,  it does not crash the server, rolling back to the previous version does remove the issue.  It does not occur in single player. 

Versions,
malisiscore-1.12.2-6.3.1
malisisdoors-1.12.2-7.2.3
forge-1.12.2-14.23.1.2587

https://pastebin.com/3T5HCfMw

**Comment by zyxifrash** [comment]
Our server is on forge 1.12.2 - 14.23.1.2555 and is showing the same issue - for some players. I'm on forge client 2585 and it does not disconnect me - but I can trigger the plates/buttons next to other players (probably on 2555 - the pack forge version) who will be disconnected. Same Malisis versions as listed by op. 

Update: It just kicked me off for the first time, not sure why the change. Log at https://pastebin.com/UD6Ys8rG, looks the same as OP
