### ISSUE TITLE
[1.12.2]Crash when Opening Rusty Hatch

### ISSUE THREAD

**Issue by AlexModGuy** [Ordinastie/MalisisDoors#216]
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.2.1-alpha-snapshot-universal.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.3.0.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 1/14/18 9:55 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.world.World.func_189509_E(World.java:224)
	at net.minecraft.world.World.func_180495_p(World.java:904)
	at net.malisis.doors.block.RustyHatch.getBoundingBoxes(RustyHatch.java:150)
	at net.malisis.doors.block.RustyHatch.func_185477_a(RustyHatch.java:189)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:453)
	at net.minecraft.world.World.func_191504_a(World.java:1335)
	at net.minecraft.world.World.func_184144_a(World.java:1359)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:720)
	at net.minecraft.client.entity.EntityPlayerSP.func_70091_d(EntityPlayerSP.java:1054)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1949)
	at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java:1827)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2384)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:513)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:1011)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:181)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.world.World.func_189509_E(World.java:224)
	at net.minecraft.world.World.func_180495_p(World.java:904)
	at net.malisis.doors.block.RustyHatch.getBoundingBoxes(RustyHatch.java:150)
	at net.malisis.doors.block.RustyHatch.func_185477_a(RustyHatch.java:189)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:453)
	at net.minecraft.world.World.func_191504_a(World.java:1335)
	at net.minecraft.world.World.func_184144_a(World.java:1359)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:720)
	at net.minecraft.client.entity.EntityPlayerSP.func_70091_d(EntityPlayerSP.java:1054)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1949)
	at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java:1827)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2384)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:513)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:1011)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:181)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 334
	Entity Name: Alexthe666
	Entity's Exact location: 2.60, 59.16, 222.51
	Entity's Block location: World: (2,59,222), Chunk: (at 2,3,14 in 0,13; contains blocks 0,0,208 to 15,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0.02, 0.12, 0.02
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Alexthe666'/334, l='MpServer', x=2.60, y=59.16, z=222.51]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (172,64,256), Chunk: (at 12,4,0 in 10,16; contains blocks 160,0,256 to 175,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 275763 game time, 339559 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 54 total; [EntitySkeleton['Skeleton'/384, l='MpServer', x=-68.50, y=44.00, z=220.50], EntityZombie['Zombie'/385, l='MpServer', x=-70.50, y=44.00, z=221.50], EntityChicken['Chicken'/386, l='MpServer', x=-71.62, y=66.00, z=211.94], EntityItem['item.item.egg'/1155, l='MpServer', x=-17.56, y=65.00, z=191.38], EntityItem['item.item.egg'/1157, l='MpServer', x=32.29, y=62.94, z=248.28], EntityCow['Cow'/390, l='MpServer', x=-72.58, y=101.00, z=173.78], EntityChicken['Chicken'/13, l='MpServer', x=-18.14, y=66.00, z=190.32], EntitySheep['Sheep'/398, l='MpServer', x=-62.39, y=66.00, z=248.77], EntitySheep['Sheep'/399, l='MpServer', x=-62.73, y=66.00, z=253.54], EntityChicken['Chicken'/15, l='MpServer', x=-28.11, y=64.00, z=254.64], EntitySheep['Sheep'/400, l='MpServer', x=-58.75, y=65.00, z=255.49], EntitySkeleton['Skeleton'/17, l='MpServer', x=-20.50, y=65.00, z=293.50], EntityCreeper['Creeper'/18, l='MpServer', x=-24.50, y=65.00, z=294.50], EntityCow['Cow'/405, l='MpServer', x=-63.53, y=109.00, z=173.81], EntitySheep['Sheep'/411, l='MpServer', x=-59.51, y=67.00, z=227.73], EntityZombie['Zombie'/39, l='MpServer', x=-13.48, y=14.00, z=143.17], EntityChicken['Chicken'/42, l='MpServer', x=-6.34, y=67.00, z=278.88], EntityItem['item.item.egg'/963, l='MpServer', x=43.68, y=63.00, z=206.33], EntityChicken['Chicken'/70, l='MpServer', x=8.58, y=63.00, z=177.82], EntityChicken['Chicken'/76, l='MpServer', x=8.24, y=65.00, z=286.51], EntityChicken['Chicken'/77, l='MpServer', x=3.97, y=64.00, z=287.74], EntityChicken['Chicken'/78, l='MpServer', x=4.24, y=66.00, z=277.11], EntityPlayerSP['Alexthe666'/334, l='MpServer', x=2.60, y=59.16, z=222.51], EntityChicken['Chicken'/79, l='MpServer', x=11.82, y=66.00, z=282.77], EntityCow['Cow'/337, l='MpServer', x=-75.79, y=64.00, z=288.53], EntitySpider['Spider'/81, l='MpServer', x=2.50, y=63.00, z=300.50], EntityChicken['Chicken'/82, l='MpServer', x=7.26, y=65.00, z=290.13], EntityCow['Cow'/338, l='MpServer', x=-77.23, y=64.00, z=289.49], EntityChicken['Chicken'/348, l='MpServer', x=-41.52, y=63.00, z=269.70], EntityChicken['Chicken'/349, l='MpServer', x=-43.91, y=65.00, z=259.84], EntityChicken['Chicken'/350, l='MpServer', x=-43.50, y=65.00, z=262.56], EntityZombie['Zombie'/351, l='MpServer', x=-64.14, y=44.00, z=224.56], EntityChicken['Chicken'/95, l='MpServer', x=18.88, y=64.00, z=156.88], EntityItem['item.item.egg'/1119, l='MpServer', x=-28.80, y=65.00, z=250.85], EntityChicken['Chicken'/96, l='MpServer', x=25.50, y=63.00, z=162.50], EntityChicken['Chicken'/97, l='MpServer', x=25.50, y=63.00, z=162.50], EntityChicken['Chicken'/98, l='MpServer', x=21.17, y=65.00, z=283.48], EntityChicken['Chicken'/99, l='MpServer', x=18.79, y=66.00, z=286.50], EntityCow['Cow'/100, l='MpServer', x=21.45, y=62.63, z=300.39], EntityChicken['Chicken'/357, l='MpServer', x=-71.59, y=65.00, z=203.49], EntityChicken['Chicken'/101, l='MpServer', x=20.89, y=65.00, z=288.41], EntityCow['Cow'/102, l='MpServer', x=22.80, y=64.00, z=295.57], EntityItem['item.item.egg'/998, l='MpServer', x=-28.69, y=64.00, z=254.08], EntityCow['Cow'/103, l='MpServer', x=18.55, y=66.00, z=291.02], EntityCow['Cow'/104, l='MpServer', x=16.20, y=64.00, z=299.52], EntityChicken['Chicken'/105, l='MpServer', x=18.07, y=66.00, z=292.12], EntityCreeper['Creeper'/361, l='MpServer', x=-71.50, y=38.00, z=143.50], EntityChicken['Chicken'/116, l='MpServer', x=34.11, y=63.00, z=173.17], EntityChicken['Chicken'/117, l='MpServer', x=43.48, y=63.00, z=206.80], EntityChicken['Chicken'/119, l='MpServer', x=33.78, y=65.00, z=196.88], EntityCow['Cow'/376, l='MpServer', x=-70.24, y=63.00, z=286.24], EntityChicken['Chicken'/120, l='MpServer', x=32.91, y=62.94, z=247.73], EntityCow['Cow'/377, l='MpServer', x=-66.38, y=63.00, z=283.48], EntityChicken['Chicken'/382, l='MpServer', x=-28.53, y=65.00, z=250.49]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5277493656 bytes (5033 MB) / 8228175872 bytes (7847 MB) up to 8228175872 bytes (7847 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -Xms8G
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.1.2587 Optifine OptiFine_1.12.2_HD_U_C8 51 mods loaded, 51 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                      | Version                  | Source                                             | Signature                                |
	|:--------- |:----------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft               | 1.12.2                   | minecraft.jar                                      | None                                     |
	| UCHIJAAAA | mcp                     | 9.42                     | minecraft.jar                                      | None                                     |
	| UCHIJAAAA | FML                     | 8.0.99.99                | forge-1.12.2-14.23.1.2587.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                   | 14.23.1.2587             | forge-1.12.2-14.23.1.2587.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | mercurius_updater       | 1.0                      | MercuriusUpdater-1.12.2.jar                        | None                                     |
	| UCHIJAAAA | ic2                     | 2.8.39-ex112             | industrialcraft-2-2.8.39-ex112.jar                 | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | jei                     | 4.8.5.144                | jei_1.12.2-4.8.5.144.jar                           | None                                     |
	| UCHIJAAAA | forestry                | 5.7.0.232                | forestry_1.12.2-5.7.0.232.jar                      | None                                     |
	| UCHIJAAAA | binniecore              | unspecified              | binnie-mods-1.12.2-2.5.0.111.jar                   | None                                     |
	| UCHIJAAAA | binniedesign            | 1.0                      | binnie-mods-1.12.2-2.5.0.111.jar                   | None                                     |
	| UCHIJAAAA | genetics                | 2.5.0.111                | binnie-mods-1.12.2-2.5.0.111.jar                   | None                                     |
	| UCHIJAAAA | botany                  | 2.5.0.111                | binnie-mods-1.12.2-2.5.0.111.jar                   | None                                     |
	| UCHIJAAAA | extrabees               | 2.5.0.111                | binnie-mods-1.12.2-2.5.0.111.jar                   | None                                     |
	| UCHIJAAAA | extratrees              | 2.5.0.111                | binnie-mods-1.12.2-2.5.0.111.jar                   | None                                     |
	| UCHIJAAAA | biomesoplenty           | 7.0.1.2312               | BiomesOPlenty-1.12.2-7.0.1.2312-universal.jar      | None                                     |
	| UCHIJAAAA | buildcraftlib           | 7.99.13                  | buildcraft-core-7.99.13.jar                        | None                                     |
	| UCHIJAAAA | buildcraftcore          | 7.99.13                  | buildcraft-core-7.99.13.jar                        | None                                     |
	| UCHIJAAAA | buildcraftbuilders      | 7.99.13                  | buildcraft-builders-7.99.13.jar                    | None                                     |
	| UCHIJAAAA | buildcrafttransport     | 7.99.13                  | buildcraft-transport-7.99.13.jar                   | None                                     |
	| UCHIJAAAA | ctm                     | MC1.12-0.2.3.9           | CTM-MC1.12-0.2.3.9.jar                             | None                                     |
	| UCHIJAAAA | chisel                  | MC1.12-0.1.1.26          | Chisel-MC1.12-0.1.1.26.jar                         | None                                     |
	| UCHIJAAAA | codechickenlib          | 3.1.5.331                | CodeChickenLib-1.12.2-3.1.5.331-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux            | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar            | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | cofhcore                | 4.3.10                   | CoFHCore-1.12.2-4.3.10.4-universal.jar             | None                                     |
	| UCHIJAAAA | cofhworld               | 1.1.1                    | CoFHWorld-1.12.2-1.1.1.12-universal.jar            | None                                     |
	| UCHIJAAAA | dimdoors                | 3.0.0-beta4              | dimdoors-3.0.0-beta-4.jar                          | None                                     |
	| UCHIJAAAA | forgelin                | 1.6.0                    | Forgelin-1.6.0.jar                                 | None                                     |
	| UCHIJAAAA | llibrary                | 1.7.9                    | llibrary-1.7.9-1.12.jar                            | None                                     |
	| UCHIJAAAA | iceandfire              | 1.3.1                    | iceandfire-1.3.1-1.12.2.jar                        | None                                     |
	| UCHIJAAAA | mekanism                | 1.12.2-9.4.3.330         | Mekanism-1.12.2-9.4.3.330.jar                      | None                                     |
	| UCHIJAAAA | teslacorelib            | 1.0.12                   | tesla-core-lib-1.12-1.0.12.jar                     | None                                     |
	| UCHIJAAAA | industrialforegoing     | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.6.6-113.jar           | None                                     |
	| UCHIJAAAA | inventorytweaks         | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | ironbackpacks           | 1.12.2-3.0.2-3           | IronBackpacks-1.12.2-3.0.2-3.jar                   | None                                     |
	| UCHIJAAAA | ironchest               | 1.12.2-7.0.34.820        | ironchest-1.12.2-7.0.34.820.jar                    | None                                     |
	| UCHIJAAAA | jeibees                 | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                       | None                                     |
	| UCHIJAAAA | malisiscore             | 1.12.2-6.3.0             | malisiscore-1.12.2-6.3.0.jar                       | None                                     |
	| UCHIJAAAA | malisisdoors            | 1.12.2-7.2.2             | malisisdoors-1.12.2-7.2.2.jar                      | None                                     |
	| UCHIJAAAA | mantle                  | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                           | None                                     |
	| UCHIJAAAA | mekanismgenerators      | 9.4.3                    | MekanismGenerators-1.12.2-9.4.3.330.jar            | None                                     |
	| UCHIJAAAA | mekanismtools           | 9.4.3                    | MekanismTools-1.12.2-9.4.3.330.jar                 | None                                     |
	| UCHIJAAAA | tconstruct              | 1.12.2-2.9.0.55          | TConstruct-1.12.2-2.9.0.55.jar                     | None                                     |
	| UCHIJAAAA | thebetweenlands         | 3.2.1-alpha-snapshot     | TheBetweenlands-3.2.1-alpha-snapshot-universal.jar | None                                     |
	| UCHIJAAAA | thermalfoundation       | 2.3.10                   | ThermalFoundation-1.12.2-2.3.10.6-universal.jar    | None                                     |
	| UCHIJAAAA | thermaldynamics         | 2.3.10                   | ThermalDynamics-1.12.2-2.3.10.4-universal.jar      | None                                     |
	| UCHIJAAAA | bspkrscore              | at_0.9                   | Treecapitator-1.12-at_0.9a.jar                     | None                                     |
	| UCHIJAAAA | treecapitator           | at_0.9                   | Treecapitator-1.12-at_0.9a.jar                     | None                                     |
	| UCHIJAAAA | twilightforest          | 3.5.263                  | twilightforest-1.12.2-3.5.263-universal.jar        | None                                     |
	| UCHIJAAAA | wawla                   | 2.5.248                  | Wawla-1.12.2-2.5.248.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | xaerominimap            | 1.14.5                   | Xaeros_Minimap_1.14.5_Forge_1.12.jar               | None                                     |
	| UCHIJAAAA | teslacorelib_registries | 1.0.12                   | tesla-core-lib-1.12-1.0.12.jar                     | None                                     |

	Loaded coremods (and transformers): 
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.2.1-alpha-snapshot-universal.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.3.0.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 376.67' Renderer: 'GeForce GTX 960M/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.1.2587
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960M/PCIe/SSE2 GL version 4.5.0 NVIDIA 376.67, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C8
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 376.67
	OpenGlRenderer: GeForce GTX 960M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8`

**Comment by Ordinastie** [comment]
Please make sure you're using latest version before creating issues. This has already been fixed.

**Comment by AlexModGuy** [comment]
thanks.
