### ISSUE TITLE
Incompatibilities with quark

### ISSUE THREAD

**Issue by ChellieH** [Ordinastie/MalisisDoors#218]
I tried to run this mod with quark but there are a few instances where either both mods try to do the same thing or there are items with identical recipes. I'm not sure if this is a complete list but these are the ones that I have found.
Both mods add wood specific trap doors - not a big deal as this can probably be turned off with the configs and is going to become a vanilla thing soon
Both mods make double doors open together - I think I've seen somewhere that this can be turned off in quark config.
Both mods have a type of iron ladder with the same recipe - This one is a pretty big conflict for me as the quark iron ladders have different properties to malisis doors iron ladders and I would love to have both but at the moment i have to turn off malisis doors to get the quark iron ladder to craft.

**Comment by Ordinastie** [comment]
Usually people use CraftTweaker or similar to handle conflict recipes.
