### ISSUE TITLE
Redstone or Pressure Plate won't close fence gates 

### ISSUE THREAD

**Issue by trilexcom** [Ordinastie/MalisisDoors#220]
hi MalisisDoor / Ordinastie 

After Updting to MalisisDoors and MalisisCore. redstone or pressure plate won't close or open them. 

Version : 2-6.3.2 for MalisisCore 
Version : 2.2.7.2.4 for MalisisDoor

Forge version : 2582

Pack : Trilex Pack version 1.5 

crashlog info : https://pastebin.com/PnEjwTRj

Mat (Trilex)

**Comment by Ordinastie** [comment]
Can you provide full log please ?

**Comment by trilexcom** [comment]
i dont mean to ask the dumb question where do i get the full log for you sorry to ask.

**Comment by trilexcom** [comment]
here is the server log let me know if this is enough http://www.filedropper.com/showdownload.php/logs_16

**Comment by Ordinastie** [comment]
Yeah, nothing in the log, which is not surprising... I should have read the crash report better : 
"Description: Manually triggered debug crash"

**Comment by trilexcom** [comment]
ok how can i help you ? if i downgrade the version its working fine but after upgrading her she is working ok? what else would you like me to provide you for assistance? Mat

**Comment by trilexcom** [comment]
Thanks

On Jan 17, 2018 11:56 AM, "Ordinastie" <notifications@github.com> wrote:

Closed #220 <https://github.com/Ordinastie/MalisisDoors/issues/220> via
56ef8bf
<https://github.com/Ordinastie/MalisisDoors/commit/56ef8bfb4c579265161979b27e3ee8a1f9049d66>
.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ordinastie/MalisisDoors/issues/220#event-1428701660>,
or mute the thread
