### ISSUE TITLE
Support For Other Mods

### ISSUE THREAD

**Issue by ghost** [Ordinastie/MalisisDoors#221]
like Forestry, Natura or Terraqueous. can you add door opening/closing animation for their doors please? it would be lovely. thanks

**Comment by Ordinastie** [comment]
This has to be done by those mods authors. I already added an easy way for them to implement it, but I can't do it for them.

**Comment by ElvenChaos** [comment]
@Ordinastie Should this ticket be re-opened? So far (at time of writing), Forestry and Integrated Dynamics have said that they are open to a PR on the matter. No comments from BoP or Natura yet, but it has only been 4 hours since their respective requests have been opened.

**Comment by ghost** [comment]
BoP, Natura, Terraqueous and Forestry. That's all i want xD I really hope they will be supported.

**Comment by ElvenChaos** [comment]
@kenijey I'm not using terraqueous, so I'm not in position to submit a ticket. If you haven't done so already, you should submit a ticket on their github. I've already submitted tickets on the others.

**Comment by josephcsible** [comment]
@Ordinastie Is the way that other mod authors should add support documented anywhere? Alternatively, do you know of any open-source mods that have already done this?

**Comment by ElvenChaos** [comment]
@Ordinastie Update on the BoP ticket here: https://github.com/Glitchfiend/BiomesOPlenty/issues/1181#event-1500414510

**Comment by axieum** [comment]
Just had a look at the source code, and do not see any form of API :'(
