### ISSUE TITLE
Door Sensor Missing

### ISSUE THREAD

**Issue by andsim** [Ordinastie/MalisisDoors#224]
I notices there no door sensor why?
it was very useful
i am using malisisdoors-1.12.2-7.2.4

**Comment by Ordinastie** [comment]
Because it was moved to MalisisBlocks since 1.8 or something.
http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2558284-malisisblocks-1-12-2-6-0-3-1-11-2-5-1-0-10-12-2017
