### ISSUE TITLE
TrapDoorTileEntity is missing a mapping! - Crash

### ISSUE THREAD

**Issue by JasonMcRay** [Ordinastie/MalisisDoors#23]
http://pastebin.com/be5Ddv09

Using Malisis Doors 1.4.2
Forge 10.13.2.1263

Happened pretty much randomly on the server. I saw an 1.4.3 update of Malisis with changelog: Fixed crash on dedi servers, but when looking in the commit https://github.com/Ordinastie/MalisisDoors/commit/9a6df1f0921d4466cb4252d68cf2410345d3b0f5 so I am not sure if its the same. :)

**Comment by Ordinastie** [comment]
That shouldn't be possible. Could you provide full log to see if maybe there is something else messing with the registry ?

**Comment by JasonMcRay** [comment]
Here it is: https://www.dropbox.com/s/to1taq97xtkneze/fml-server-3.log?dl=0

**Comment by JasonMcRay** [comment]
I am going through all issues reported for my modpack, so just would like to ask. Any progress with this crash @Ordinastie?

**Comment by JasonMcRay** [comment]
Players are saying it is no longer happening. Gonna close it.
