### ISSUE TITLE
Malisis Doors Maven

### ISSUE THREAD

**Issue by Wyn-Price** [Ordinastie/MalisisDoors#238]
Hi! 
Im the 1.10+ author of SecretRoomsMod, and as the original mod had Malisis Doors support, so should the new version. However I cannot seem to find the Malisis Doors Maven. You used to have a forge maven ([here](http://files.minecraftforge.net/maven/net/malisis/malisisdoors/), but that seems to have stopped in version 1.8-2.4.3.If you have a new maven or whatever then point me towards it. Otherwise, if im doing somthing wrong (also a possibility) then just say so and i can probally figure it all out. 

Also I might end up needing some help while creating the Malisis Doors support. If I do I'll just create an issue or somthing.

**Comment by Ordinastie** [comment]
I pretty much stopped uploading MalisisDoors to maven as there was not much point in doing so.
You might need to manually download the jar.

Don't hesitate to come to #malisis on Esper.net if you need any help

**Comment by Wyn-Price** [comment]
I can probably use the curseforge maven, though I've been told it can be inefficient. I'll be sure to hit you up if I need help with anything
