### ISSUE TITLE
[1.7.10]please help - compile

### ISSUE THREAD

**Issue by Cronosus** [Ordinastie/MalisisDoors#243]
Hello
i trying to compile mod with malissiscore 0.14.3.dev as dependency, but it makes this error:
<code>:compileJava
.\net\malisis\doors\ProxyAccess.java:136: error: ProxyBlockAccess is not abstract and does not override abstract method isSideSolid(int,int,int,ForgeDirection,boolean) in IBlockAccess
        private static class ProxyBlockAccess implements IBlockAccess
                       ^
.\net\malisis\doors\ProxyAccess.java:168: error: ProxyWorld is not abstract and does not override abstract method getEntityByID(int) in World
        private static class ProxyWorld extends World
                       ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
:compileJava FAILED</code>

any help?

**Comment by Ordinastie** [comment]
I would say, don't dev for 1.7.10... 

As for the error, it's because I used lombok for its @Delegate annotation.

**Comment by Cronosus** [comment]
hmm..
i already have added this to dependency too
    compile 'org.projectlombok:lombok:1.14.8'

**Comment by Ordinastie** [comment]
I'm not sure then. I'll guess you'll have to fall back to my first advice : don't dev for a dead version.

**Comment by Cronosus** [comment]
i know, but i not have other choice, its for server with mods which exists only for 1.7.10.. :/

**Comment by Ordinastie** [comment]
Yes, you have the choice of not using those dead mods, and update.
