### ISSUE TITLE
Startup loading crash

### ISSUE THREAD

**Issue by EternalBlessing** [Ordinastie/MalisisDoors#244]
Click play and after about 30 seconds of loading via forge it crashes with this ... 
[crash-2018-03-20_05.09.59-client.txt](https://github.com/Ordinastie/MalisisDoors/files/1828622/crash-2018-03-20_05.09.59-client.txt)
Not sure if it'll be helpful but it only crashes when i have Optifine installed if that matters.

**Comment by Ordinastie** [comment]
Yes, it's because of Optifine. You need to update Optifine.
