### ISSUE TITLE
CRASH WHILE LOADING MODS

### ISSUE THREAD

**Issue by mr2meowsYT** [Ordinastie/MalisisDoors#294]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MalisisDoors (malisisdoors)

**Comment by Glitchster00** [comment]
I am having a similar problem but temporarily disabling Malisis doors fixes it, unfortunately, once you add it back in the crashing begins again. I have tried the modpack I'm using on multiple other computers and they have no issues.

here is a link to the modpack I use if it helps: 
https://www.curseforge.com/minecraft/modpacks/manncraft-lite 

and the crash report:
[crash-2019-04-09_01.32.45-client.txt](https://github.com/Ordinastie/MalisisDoors/files/3060511/crash-2019-04-09_01.32.45-client.txt)

**Comment by Glitchster00** [comment]
ok wait...

this may sound weird but I think I fixed it

I made a new custom modpack in the twitch launcher added Malisis doors and Malisis core and launched it, once it successfully launched I tried launching the broken modpack and to my utter shock, it just works now. No idea why.

hope this helps
