### ISSUE TITLE
MalisisDoors conflicting with AstralSorcery (1.12.2)

### ISSUE THREAD

**Issue by Sventecc** [Ordinastie/MalisisDoors#298]
I added MalisisDoors to my Direwolf20 Pack and everytime I try to start, it crashes! I figured out that those two mods (Malisis and Astral) won´t work together... I also tried it with different versions of these mods but nothing solved this issue. Please fix the bug, because there is no other mod that adds such nice doors!

**Comment by ghost** [comment]
Weird... I've used MD in the DW20 and I've got it in E2E which also has AS...
If you want traction, I'd suggest posting a pastebin link to the crash report and/or log. The dev here is a pretty quiet, but someone else might help you resolve it. ;)

**Comment by ate0ate** [comment]
I gotta say I play a custom pack with 300+ mods, including Astral Sorcery and Malisis Core/Doors/Blocks/Switches, all without issue. That said, there could indeed be another mod responsible for a conflict occurring. With very large packs it is not uncommon that mods that usually play nicely together run into some issues. As scribbler957 said, there's really no telling what is going on at all without a crash report or some logs though.
