### ISSUE TITLE
Null pointer within your ProxyWorld

### ISSUE THREAD

**Issue by TheDrunkMafia** [Ordinastie/MalisisDoors#32]
You need to add a null check for tempCache in your ProxyWorld class: https://github.com/Ordinastie/MalisisDoors/blob/master/source/net/malisis/doors/ProxyAccess.java#L235

Otherwise a null pointer seems to be thrown when it is called, an instance of this happening is when my mod calls that function to generate a string for my data. Crash report given: http://pastebin.com/XRwzS5Pz

**Comment by Ordinastie** [comment]
Should be fixed in the next version.
