### ISSUE TITLE
Problem with block rendering

### ISSUE THREAD

**Issue by NitroxydeX** [Ordinastie/MalisisDoors#33]
Hey,

is this a known issue or is there a way to prevent/fix this?

![2015-05-21_16 07 59](https://cloud.githubusercontent.com/assets/9305576/7750438/72269166-ffd4-11e4-87a6-99061f1e2fe1.png)

**Comment by Ordinastie** [comment]
I have no idea what caused this. Can you reproduce this bug reliably? Does it happen with only MalisisDoors?
If so, can you tell me exactly what you do to make it happen?

**Comment by NitroxydeX** [comment]
This is a Modpack-Server and I dont know what it make happen. Really strange. If your replace the Stonebricks block at the side: It's rendered. But if you leave the area and come back it's like on the screenshot.

**Comment by JasonMcRay** [comment]
I was having similiar issue wih Chisel blocks. It turns out it was optifine and its Multi-core chunloading. If you have Optifine, try to Set the Chunkloading to Smooth.

**Comment by NitroxydeX** [comment]
@JasonMcRay I have same problems with Chisel and Optifine. But it's not it's Multi-Core chunkloading thing. Sometimes this also bugs without optifine on chisel.

**Comment by Ordinastie** [comment]
Please reopen if issue still happens.
