### ISSUE TITLE
[Dupe] BlockBreaking

### ISSUE THREAD

**Issue by linkinkov** [Ordinastie/MalisisDoors#38]
Hello! Please add to all mechanical close inventory then other players block break.
Because can dupe all blocks.

**Comment by Ordinastie** [comment]
I don't understand at all what you said...

**Comment by linkinkov** [comment]
Sorry for my english. 
I do video:
https://youtu.be/IxYw1CLX79o

**Comment by Ordinastie** [comment]
Ok, thanks, I'll fix that soon.

**Comment by linkinkov** [comment]
Thank you, waiting so much :+1:

**Comment by linkinkov** [comment]
I see a lot of commits, then dupe will be fixed?

**Comment by linkinkov** [comment]
@Ordinastie :(

**Comment by Ordinastie** [comment]
Sorry I forgot, it's already fixed in the last update of MalisisCore :)
