### ISSUE TITLE
[minor] Error on placing malisis blocks in ocuppied space

### ISSUE THREAD

**Issue by JasonMcRay** [Ordinastie/MalisisDoors#41]
Just minor issue, when I try to place any malisis door on the spot where is player standing it gives error in log:
`[20:29:45] [Client thread/ERROR] [malisiscore]: Tried to get VanishingTileEntity at -1459,4,-84, but found TileHidden instead.`

in versions before this caused players for some reason to be kicked out from the server with "timeout" message and this spammed in the log

Core: 0.12.5
Doors: 1.9.3
Forge: 1490

**Comment by Ordinastie** [comment]
Fixed.
