### ISSUE TITLE
Game crashes on death by a creeper explosion

### ISSUE THREAD

**Issue by DestinyPlayer** [Ordinastie/MalisisDoors#42]
Every time a creeper explodes and kills me, it crashes the game fully. There are a few custom doors nearby (even though the explosion doesn't reach them), and a rusty hatch (even further).

Crash log:
https://dl.dropboxusercontent.com/u/77108893/crash-2015-07-16_22.45.49-client.txt

**Comment by Ordinastie** [comment]
Try using latest version and reopen this issue if it still happens. (But I'm pretty sure the issue comes from ProjectRed).
