### ISSUE TITLE
Client crash in single player launching world at net.malisis.core.util.chunkblock.ChunkBlockHandler.getAffectedChunks(ChunkBlockHandler.java:320)

### ISSUE THREAD

**Issue by ProsperCraft** [Ordinastie/MalisisDoors#44]
This is a clean world with no doors placed.

http://pastebin.com/TMnTKWLj

**Comment by ProsperCraft** [comment]
This started when I added INpureCore-[1.7.10]1.0.0B9-62.jar

Quit when I removed it.

**Comment by Ordinastie** [comment]
Caused by at bspkrs.util.FakeWorld.func_72945_a(FakeWorld.java:367)
bspkrs's FakeWorld doesn't give a Provider as it should.
