### ISSUE TITLE
Curtain recipe clash with Extra Utilities

### ISSUE THREAD

**Issue by Zaflis** [Ordinastie/MalisisDoors#45]
Curtains from Extra Utilities mod also use 6 wool in recipe, exactly on the left side of the grid. While blocking light they are also used for crafting dark glass, but now i can't cause this mod overrides curtain.

malisisdoors-1.7.10-1.9.3
extrautilities-1.2.8

**Comment by Ordinastie** [comment]
You would need to use a mod like MineTweaker to modify the recipes. I can't adapt to every possible mod available, so it's up to the users to resolve those kinds of conflicts.

**Comment by Zaflis** [comment]
It would be quite simple to maybe replace the bottom middle wool with 1 string, it would also represent this curtain better in my opinion. Extra Utilities is a very major mod in roughly every modpack, and had the recipe for much longer. Please do reconsider, it effects pretty much everyone who uses your mod. Can't ask everyone to install MineTweaker do you?

**Comment by Ordinastie** [comment]
And then, you have X other mod that uses that string recipe, so I change it to something else, then it's Y other mod etc, etc...
It's endless, that's why there is a mod that lets you change the recipes yourself, because as I previously said, you can't take in account every single recipe of every single mod.

**Comment by Zaflis** [comment]
You are exaggerating, there are no other mods that have the recipe, and you aren't even trying to play along with others. You would make a recipe with 8 cobblestones in a ring for item X and tell others to make a new recipe for furnace? And if it was some other mod as unknown as this that was clashing, i would propably agree with you. We are talking about a mod that is in the very core of modded Minecraft you are stepping on. Ender quarries and pumps, Magnum torches, cursed earth, builders wand... how many modpacks are there without them? I don't understand why you are so hesitant on the change.
