### ISSUE TITLE
1.9.3 - Rusty Hatch Hitbox

### ISSUE THREAD

**Issue by LazerusKI** [Ordinastie/MalisisDoors#46]
Just updated to 1.9.3 and noticed, that my Rusty Hatch that i placed with 1.7.1 acts strange.

Suddenly i could not climb through it anymore, it looked opened but the hitbox was still as if it was closed.
When i tried walking on it, it wobbled me around like what happens when you step into a chunkerror.

Also removing it was pretty tricky, since i could not "target" it. I had to find a very specific angle from where i could "see" it again

**Comment by xenoflot** [comment]
I too am encountering this problem. core 0.12.5, doors 1.9.3

**Comment by Ordinastie** [comment]
Fixed in 1.7.10-1.9.4
