### ISSUE TITLE
Recipe for Curtains conflicts with Extra Utilities Blackout curtains

### ISSUE THREAD

**Issue by plazia** [Ordinastie/MalisisDoors#47]
malisisdoors-1.7.10-1.9.4
malisiscore-1.7.10-0.12.7

Unable to craft ExU Blackout curtains with the 6 wool vertically as it creates malisis curtains. Is there any way around this?

**Comment by Ordinastie** [comment]
Yes, you can use mods like MineTweaker to change recipes.
