### ISSUE TITLE
[Suggestion] Carriage doors - redstone control and matching blocks

### ISSUE THREAD

**Issue by xenoflot** [Ordinastie/MalisisDoors#49]
Howdy, love the mod, thanks!

I used the Carriage doors on a project today but I encountered two quirks. Firstly they don't seem to respond to redstone. I'd love to put some pressure plates or sensors on them to auto-open and close.

(As an aside, could you add a player sensor with a greater or configurable range?)

Secondly, the frame looks great, so it'd be nice to have some blocks that will match the colour and texture. 

Cheers,
xeno

**Comment by Ordinastie** [comment]
Carriage doors now have configurable frames (via their recipe).
However, I don't plan on making them react to redstone.
