### ISSUE TITLE
Multiplayer Recipe Bug

### ISSUE THREAD

**Issue by CandiceJoy** [Ordinastie/MalisisDoors#51]
In single player this works fine, but in multiplayer when I try to make malisisdoors doors (through recipes, say, 6 spruce wood = 1 spruce door), it shows that that's what I'll get, but when I click on it to pull it out, it instantly converts to a vanilla door.  The same bug occurs in vanilla crafting tables as well as TiCon ones.  I can try to collect more information if you need it to track down the problem.

Malisis Core v0.12.9
Malisis Doors v1.9.5

**Comment by Ordinastie** [comment]
I assume it's been fixed. Reopen if not.
