### ISSUE TITLE
A Malis Door made with Pnematicraft Compressed Iron Blocks crashes the client

### ISSUE THREAD

**Issue by JasonMcRay** [Ordinastie/MalisisDoors#55]
Used a Malis Door Factory to create a Compressed Iron Block (PneumaticCraft) door with Spruce wood frame. Accidentally dropped the door on the ground and client immediately crashed. Tried to log back in, crash again.

When other player load the chunk where the door was on the ground = client crash.

Client Crash log here: http://pastebin.com/zZN6Hj5G
Part of server log from the time the crash occured: http://pastebin.com/h8MePzXN

MDoors: 1.10
MCore: 0.12.9
Forge: 1490

**Comment by Ordinastie** [comment]
TileEntity type should be checked before being used. Can't do it on my side.

**Comment by MJRLegends** [comment]
I know this is a very old issue, but i just tested it and i still crash when using CompressedIronBlock in a door

Crash log: https://paste.ee/p/WJQ3n

MC Version: 1.7.10
Forge: 10.13.4.1614
PneumaticCraft: 1.12.7-150
Malisis Doors: 1.7.10-1.13.2
Malisis Core: 1.7.10-0.14.3
