### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Nateolocity** [Ordinastie/MalisisDoors#57]
https://github.com/chylex/Hardcore-Ender-Expansion/issues/149

The link for the crash log is on that link on the first post. I opened the crash in OpenEye and it said the crash had to do with HEE and Malisis mods.

Thanks!

**Comment by Ordinastie** [comment]
The issue is already fixed, but I didn't have time to release a new version with the fix yet.
Thanks for the input though :)
