### ISSUE TITLE
[SUGGESTION] Alter curtain recipe to not conflict with ExtraUtilities

### ISSUE THREAD

**Issue by hron84** [Ordinastie/MalisisDoors#58]
ExtraUtilities and MalisisDoors both have a curtain (ExU calls it as "Blackout Curtain") and the recipe is exaclty same. Could you please alter your recipe to not conflict if ExtraUtilities installed? E.g. make one wool discount?

Mod versions:

ExtraUtilities 1.2.9
MalisisDoors 1.10.1

Modpack: FTB Direwolf20 1.7.10 v1.7.0

**Comment by Ordinastie** [comment]
No, I won't alter the recipe because there will always be conflicts between mods. 
However, some mods, like MineTweaker allow you to change the recipe as it pleases you.
