### ISSUE TITLE
Garage door crash. 

### ISSUE THREAD

**Issue by Claycorp** [Ordinastie/MalisisDoors#60]
When placing a door with redstone paste under it and removing the paste. Seems to happen with any item from redstone paste also.

http://pastebin.com/uTSrnhSd

EDIT: Changing door void auto fill to false will fix it from happening but not fix broken worlds.

**Comment by Ordinastie** [comment]
Except it is not my code :)
com.carpentersblocks.data.GarageDoor.

**Comment by Claycorp** [comment]
Oh shit... -.- Sorry...
