### ISSUE TITLE
Crash on Placing Vanilla Gate

### ISSUE THREAD

**Issue by CandiceJoy** [Ordinastie/MalisisDoors#63]
http://pastebin.com/iFPVmn5a

**Comment by Claycorp** [comment]
Also having this issue. Will crash servers. http://pastebin.com/VLEfEkTu

**Comment by SirFlip** [comment]
We are having a similar problem.
It looks like a Ghast shot a Fireball on a gate.
https://pastebin.com/GiZqC2wF

**Comment by Ordinastie** [comment]
Fixed.
