### ISSUE TITLE
Another Gate related crash

### ISSUE THREAD

**Issue by JasonMcRay** [Ordinastie/MalisisDoors#64]
I have placed in creative Camo Gate and when I tried to break it my client crashed. And i no longer can load that world.

Crash-log: https://paste.ee/p/zA0P4
MCore: 0.13.1
MDoors: 1.12.2

(I am seeing quite a lot of these crashes on the tracker, so not sure if anyone is the same or related)

**Comment by Ordinastie** [comment]
Will be fixed in the next update.
