### ISSUE TITLE
A critical problem occurred registering the ASM transformer class

### ISSUE THREAD

**Issue by Tsyklop** [Ordinastie/MalisisDoors#66]
error in the log file:
http://pastebin.com/ZrrP8ntw

malisiscore-1.7.10-0.14.0 malisisdoors-1.7.10-1.13.0

**Comment by liach** [comment]
It should be an issue with cofhcore.

**Comment by Tsyklop** [comment]
@liach Set in an error malisiscore.

**Comment by skyboy** [comment]
Your main ASM class needs this annotation on it: `@IFMLLoadingPlugin.TransformerExclusions({ "net.malisis.core.asm." })`

**Comment by liach** [comment]
@skyboy  There is TransformerExclusions annotation already. https://github.com/Ordinastie/MalisisCore/blob/1.7/src/main/java/net/malisis/core/asm/MalisisCorePlugin.java#L33

**Comment by skyboy** [comment]
Ah, your ASM transformers aren't in a package covered by that, but extend classes that are.

**Comment by Ordinastie** [comment]
Except, it's actually not really needed.
It's only because of some CoFH weird stuff they're doing : 
https://github.com/CoFH/CoFHCore/blob/master/src/main/java/cofh/asm/CoFHAccessTransformer.java#L79-L101
