### ISSUE TITLE
Fence gates don't connect to fences and walls

### ISSUE THREAD

**Issue by mmelvin0** [Ordinastie/MalisisDoors#67]
MalisisDoors gate in the foreground, vanilla in the background: http://i.imgur.com/UY379aI.jpg

This is with MalisisCore 0.14.0 and MalisisDoors 1.13.0. I tried with each combination of enableCamoFenceGate and modifyVanillaDoors.

**Comment by Ordinastie** [comment]
Fixed in 1.8, not fixable for 1.7.10.
