### ISSUE TITLE
[1.7.10-1.13.0] Trapdoors generated as part of a structure are spawn in the closed position

### ISSUE THREAD

**Issue by nmarshall23** [Ordinastie/MalisisDoors#69]
To reproduce install RecurrentComplex and spawn in one of the houses. The trapdoors aka, window shutters will be generated in the closed position. 

When I remove MalisisDoors they are spawned in the expected open position.

I have also seen this in structures generated by Roguelike Dungeons.

**Comment by SeriousCreeper** [comment]
Similiar here, in 1.10.2. I remember this being an issue for a while too. 

The colliders display the right position but the actual block is reversed:
http://i.imgur.com/W1zhaUh.png

Those trapdoors should be facing down, like the collider highlighted.

**Comment by Ordinastie** [comment]
Is there any Vanilla structure that spawns open trapdoors ?

**Comment by SeriousCreeper** [comment]
Hm villages seem fine, don't think they have trapdoors but doors are usually affected by this as well (being reversed). But yeah, vanilla villages are fine. 

Any other structure generation seems to be affected. The buildings from Harvest Festival do it, Recurrent Complex and Roguelike Dungeons do it as well, even copying structures into a world using WorldEdit reverses them.

**Comment by nmarshall23** [comment]
Was a fixed found?

**Comment by Ordinastie** [comment]
I think it has been fixed in latest versions, but not for 1.7.10 as it has been discontinued for quite some time now.
And I might be mistaken, but I think it was fixed in RC directly.
