### ISSUE TITLE
client crash ProxyAccess.java:170

### ISSUE THREAD

**Issue by hunter688** [Ordinastie/MalisisDoors#70]
http://pastebin.com/LjMLiMWd

http://pastebin.com/J7uwKxY4

http://pastebin.com/TLtsrMLZ

Client crashes due diamond vanishing frame with sand block inside.
When vanishing blocks are removed from map, client does not crashed anymore.

**Comment by Ordinastie** [comment]
I assume it's fixed. Reopen if not.
