### ISSUE TITLE
[1.8.9] Extreme FPS drop glitch

### ISSUE THREAD

**Issue by sblectric** [Ordinastie/MalisisDoors#72]
When at a certain distance and angle from a Malisis door, the client frame rate drops considerably. Exiting the area brings the FPS back up again, but reentering makes it drop again. This may also affect the server side, but that is unknown.

When MalisisDoors is removed, the glitch no longer exists.

MalisisDoors 3.0.0
MalisisCore 2.0.1

**Comment by Ordinastie** [comment]
I will need a bit more details if I want to be able to reproduce that.

**Comment by sblectric** [comment]
This occured while on a server. Otherwise it's difficult to describe, it seemingly is in random positions near doors in the world, but is entirely consistent, i.e. reentering that spot lags everything again.

**Comment by Ordinastie** [comment]
Can you reproduce it on another world ? Can you reproduce it with only MalisisDoors installed ?
Did you place thousands of doors ? etc..

**Comment by Cracks777** [comment]
this happens on 1.7.10 also, if you place more than 10 doors in a chunk it drops to around 30 fps from 250~
 But not all doors cause this, the saloon doors are one that does

**Comment by Cracks777** [comment]
to reproduce, make a new world, hit F3 watch fps, place 5-10 saloon doors and fps will drop really bad.

**Comment by Cracks777** [comment]
ill upload a video.

**Comment by Cracks777** [comment]
https://youtu.be/nPXg0pZh8ZI

**Comment by Ordinastie** [comment]
Fixed it for 1.7.10, but it's unrelated to 1.8.9 case.

**Comment by Cracks777** [comment]
is it fixed for all doors or just the saloon door?

**Comment by Cracks777** [comment]
testing now
...

**Comment by Ordinastie** [comment]
That was an issue with Saloon Doors only.

**Comment by Ordinastie** [comment]
Please reopen if it's still happening for other doors, in the latest version.

**Comment by pressRtowin** [comment]
This is happening for me with the large dark oak wooden doors. Frames drop to less than 1fps if a handful of them are in an area. More than likely all the large double doors cause this. I only extensively tested with the dark oak ones. (this is on 1.12 though)
