### ISSUE TITLE
1.8.9-Double Door Closing

### ISSUE THREAD

**Issue by WenXin20** [Ordinastie/MalisisDoors#73]
Once open, it's impossible to close double doors with your hand.

**Comment by Ordinastie** [comment]
Please provide full log, and detailed description of what you did.

**Comment by WenXin20** [comment]
I placed an oak door next to another one, opened it, then tried closing it, but it wouldn't. Probably a conflict with another mod, because when tested w/ only malisis mods and optifine, it worked fine

**Comment by Ordinastie** [comment]
Well, if you can pinpoint what mod, and provide a full log, I can try to find out what's wrong.

**Comment by WenXin20** [comment]
I found out it is the charset mod that causes this. (http://charset.asie.pl/)
(Requires MCMultipart [http://minecraft.curseforge.com/projects/mcmultipart]) 
Log:
(https://github.com/Ordinastie/MalisisDoors/files/145626/fml-client-latest.txt)

**Comment by Ordinastie** [comment]
Apparently, it tweaks the doors to allow double doors too, I hope disabling that in Charset will fix the problem.

**Comment by WenXin20** [comment]
Yes, it does, thanks
