### ISSUE TITLE
1.8.9-Null w/ Door Factory

### ISSUE THREAD

**Issue by WenXin20** [Ordinastie/MalisisDoors#74]
Unable to open the door factory and the block mixer from malisis blocks, it says in the chat what happened when they were right clicked. 
Pic of what happened:
(https://cloud.githubusercontent.com/assets/12000593/13273257/c04f5026-da67-11e5-9db6-599ecf4c9bbf.png)

**Comment by Ordinastie** [comment]
Please provide full log.
I assume Optifine is installed ? Does it still happen without Optifine ?

**Comment by WenXin20** [comment]
It only happens when optifine is installed.
Log: (https://github.com/Ordinastie/MalisisDoors/files/143929/latest.txt)

**Comment by Ordinastie** [comment]
Should be fixed in latest of MalisisCore.

**Comment by WenXin20** [comment]
Ok, thanks
