### ISSUE TITLE
1.8.9-Glitched Custom Doors

### ISSUE THREAD

**Issue by WenXin20** [Ordinastie/MalisisDoors#75]
After placing a custom door (Right of photo), it's impossible to right click them to open, if redstone is used, the door becomes a door with glass for the top and bottom with an oak planks frame (Left of photo), which is unable to be clicked or even selected and can be walked through. It acts as if it isn't there. (https://cloud.githubusercontent.com/assets/12000593/13338074/c03d3232-dbe4-11e5-8c62-7c142aa669fe.png)

**Comment by Ordinastie** [comment]
Fixed in 1.8.9-3.0.1.

**Comment by WenXin20** [comment]
K, thanks

**Comment by WenXin20** [comment]
Ì can't find that file on curseforge.

**Comment by Ordinastie** [comment]
Apparently, it didn't upload... It should be up in a few minutes.

**Comment by WenXin20** [comment]
Ok, thanks
