### ISSUE TITLE
1.8.9 Server crash

### ISSUE THREAD

**Issue by kwpugh** [Ordinastie/MalisisDoors#76]
Crash report: http://pastebin.com/raw/YJv1WDGq

**Comment by Ordinastie** [comment]
Can you make sure it still happens in the latest version ?

**Comment by kwpugh** [comment]
Just saw that you released a new version.   I will check on it.

**Comment by kwpugh** [comment]
I put v 3.0..1 on the server and did some testing and it doesn't seem to happen any more.

Thank you.

**Comment by sdaddy** [comment]
Just got this same crash using 3.0.1 on a server. I was mining and came to a Rogelike Dungeon. http://pastebin.com/raw/bVknLXqt

Using The Pioneers Pack - Release 4.

**Comment by kwpugh** [comment]
Were you near a spawner with a stone pressure plate on top?   That's how we encountered there error.

**Comment by sdaddy** [comment]
I'm not sure. I just came to the outside of the dungeon, but there's a bunch of spawners in the Roguelike Dungeons so it may be very likely.
