### ISSUE TITLE
garage door blocks not rendering properly.1.8.9

### ISSUE THREAD

**Issue by kotoroshinoto** [Ordinastie/MalisisDoors#77]
version 3.0.1 with malisiscore 2.0.2
if I place the garage door blocks, they are invisible and do not render. the client also seems to think they aren't present, as I cannot break them with tools. (had to use world edit to fix them

**Comment by kotoroshinoto** [comment]
I notice that when I search for the mod using JEI (using at symbol), none of hte icons are drawn at all.

**Comment by Ordinastie** [comment]
I don't have any issues with Garage Doors. Does it happen with only MalisisDoors installed ?

**Comment by kotoroshinoto** [comment]
I figured it was an interaction, but I couldn't begin to guess which mod is doing it.

**Comment by Ordinastie** [comment]
You remove half of them, if it works, it's the other half. Repeat until you have one left.
