### ISSUE TITLE
1.8.9 Render bug

### ISSUE THREAD

**Issue by reddler97** [Ordinastie/MalisisDoors#79]
I only have malisiscore v2.0.4 and malisisdoors v3.0.2 which to my knowledge are the latest. when i try to view any of the items in my inventory it crashes, this is the crash log http://pastebin.com/nRQ3FLz1

also (maybe in part of the rendering issue) When installed JEI(just enough items) doesn't display your mod's stuff

**Comment by Ordinastie** [comment]
You don't have only MalisisDoors and Core, and it's in fact IronBackPacks that is crashing.
