### ISSUE TITLE
Malisis doors and turtles

### ISSUE THREAD

**Issue by insuusvenerati** [Ordinastie/MalisisDoors#80]
When a turtle places a door next to another door it crashes the server. 

Crash report: http://pastebin.com/DDcJW8Ed
Running computer craft 1.79pr1
Malisis doors version : 3.0.1
Program being run is: http://pastebin.com/i46GCZUF
Running forge 11.15.1.1764

**Comment by Ordinastie** [comment]
Update MalisisDoors. Please reopen if it still happens with latest version.
