### ISSUE TITLE
Client crash - java.lang.IllegalArgumentException: Cannot get property PropertyBool

### ISSUE THREAD

**Issue by ProsperCraft** [Ordinastie/MalisisDoors#82]
forge-1.8.9-11.15.1.1764-universal
malisisdoors-1.8.9-3.1.1.jar

http://pastebin.com/HBWDCqfb

I was under my base mining, I don't even know if we have any doors placed yet.

**Comment by Ordinastie** [comment]
Fixed in latest version.
