### ISSUE TITLE
when I make a malisis' doors door with a ghost block as one of the parts when i place the door it crashes...

### ISSUE THREAD

**Issue by ThePokemonkey** [Ordinastie/MalisisDoors#86]
when I make a malisis' doors door with a ghost block as one of the parts when I place the door it crashes...

also, when I restart mc and load the world again, it crashes again, lost one of my worlds to it....

log is here
[ghost block crash log.txt](https://github.com/Ordinastie/MalisisDoors/files/264286/ghost.block.crash.log.txt)

if you are wondering, ghost blocks are from the secretroomsmod

**Comment by Ordinastie** [comment]
Ghost block should not be used for CustomDoors. Anyway, it's SecretRooms that should handle that crash by first making sure the TE is the one expected.
