### ISSUE TITLE
Recipes registered in PreInt phase

### ISSUE THREAD

**Issue by 31trainman** [Ordinastie/MalisisDoors#87]
Im noticing this error about recipes being registered in preint phase for your mod http://pastebin.com/UHGcWZxH upon trying to get the recipe for them via nei's r key it doesn't work

Latest Malsis doors and its addons
Mod list: http://pastebin.com/ss7RbZ2k

Forge 1614 mc 1.7.10
Java 8 update 91
Mac os x 10.11.4

**Comment by Ordinastie** [comment]
There is nothing wrong in registering recipes in preInit, contrary to what that mod spams in the log.
However, 1.7.10 is long dead now, so maybe it's time to update :)
