### ISSUE TITLE
1.7.10 Doorfactory Server - Side Crash

### ISSUE THREAD

**Issue by LordKhaox** [Ordinastie/MalisisDoors#88]
Sometimes when i rightclick the Doorfactory my game crashes and i get this crash report http://pastebin.com/fzRq13mt
seems to do something with the serverside any Idea whats happening?

**Comment by Ordinastie** [comment]
I'm not convinced the DoorFactory causes that, I think it's probably the block you had in your hand at that time.
However, 1.7.10 is long dead now, so maybe it's time to update :)
