### ISSUE TITLE
[1.7.10] Strange question

### ISSUE THREAD

**Issue by ghost** [Ordinastie/MalisisDoors#90]
Hi! Sir! Please look at the following picture, this is certainly not normal:
![1](https://cloud.githubusercontent.com/assets/20459998/16842168/ff96df30-4a0e-11e6-80e0-6847864040ae.png)
![2](https://cloud.githubusercontent.com/assets/20459998/16842165/ff8f2916-4a0e-11e6-83a5-3e21ad18968d.png)
![4](https://cloud.githubusercontent.com/assets/20459998/16842167/ff916528-4a0e-11e6-8aef-c943aa4fb158.png)
![6](https://cloud.githubusercontent.com/assets/20459998/16842166/ff8f4932-4a0e-11e6-9284-bc2b511b97a4.png)

---

**And the normal is:**

![a1](https://cloud.githubusercontent.com/assets/20459998/16842190/174c1b18-4a0f-11e6-8301-5803a44f3213.png)
![a2](https://cloud.githubusercontent.com/assets/20459998/16842191/174e89f2-4a0f-11e6-9388-b8412bea9d0f.png)
![a3](https://cloud.githubusercontent.com/assets/20459998/16842192/175988a2-4a0f-11e6-8b8a-7664e4a3a096.png)

Very humble question, but it's always a problem.

At the beginning, there was no question. But after a period of time, it appeared.
1.8 and 1.9 I have not tested, but I think it should not be normal.

**If I delete MalisisDoor, there is no problem.**

I think this is a rendering bug, please take a look for this.
Thanks!

**Comment by ghost** [comment]
@Ordinastie I know what bug is !!!!!!
**Beacon !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!**

After a long test ( Only use MalisisDoors Mod without any other mods ), I found the following questions:

---

**If I use Beacon  (If there's a beacon near the door):**

![1](https://cloud.githubusercontent.com/assets/20459998/16893416/ade22670-4b69-11e6-8e4e-850cc6a926db.png)

**Rendering bugggggggggg !!!**

---

**If I break Beacon (If there's no beacon near the door):**

![2](https://cloud.githubusercontent.com/assets/20459998/16893417/bb8885c6-4b69-11e6-877c-e821a25c7d40.png)

**Everything is normal !!!!!!!!!!!!!!!!!!!!!!!**

---

**Oh !!! The BUG is, Beacon and MalisisDoors don't know why the conflict!**

**Comment by AnrDaemon** [comment]
I've seen a similar issue. Thanks for a hint, I'm going to try some new angles to look from, as it is definitely not limited to beacon.

**Comment by darthvader45** [comment]
It seems like when certain blocks are near the doors, z-fighting occurs.  Very odd, I must say.

**Comment by AnrDaemon** [comment]
Ok, to me, it seems to be randomly occuring z-fighting.
Try restarting your client, you will likely have no issues with it for a short while.

**Comment by Ordinastie** [comment]
By default, faces are only rendered one way. Somehow the beacon changes that behavior without restoring it.
However, 1.7.10 is way too old to bother fixing it, sorry.
On a brigther note, that bug doesn't happen in 1.9.4 :)
Thanks for reporting (and investigating) anyway.
