### ISSUE TITLE
[1.10.2] Fence Gates Don't Render Open on Multiplayer

### ISSUE THREAD

**Issue by SirDavidLudwig** [Ordinastie/MalisisDoors#91]
I've been running an SMP server for a while, and I updated to the latest commits of MalisisCore [30c5085] and MalisisDoors. [ea39f29].  everything seems to work great except for fence gates.  They always render closed.  I am running this on 1.10.2, so that could be the issue, but I thought I'd report this anyway.

**Comment by Ordinastie** [comment]
Should be fixed in latest. Reopen if issue still exists.
