### ISSUE TITLE
rusty hatch crashes game when placed

### ISSUE THREAD

**Issue by 0Heatseeker0** [Ordinastie/MalisisDoors#93]

**Comment by MechaJ** [comment]
I have had the same issue, here is a crashlog for it, if it helps.  http://pastebin.ca/3671459

**Comment by Redlotus99** [comment]
I'm also getting this on my server

**Comment by Ordinastie** [comment]
@MechaJ Yes, it's definitely more helpful than the previous no description/no log post, thanks.
The crash is caused by Optifine telling me to render blocks in the world without giving me a world. I'll try to release a fix within few days.

**Comment by Redlotus99** [comment]
I apologize for not getting you a log as it was a player on my server that was having this issue. I'll see if I can get a log if needed.

**Comment by Ordinastie** [comment]
If you have Optifine installed, it's most likely the same issue.

**Comment by Hastling** [comment]
Confirmed that the latest version (1.9.4-5.0.2) fixes the issue even with Optifine installed. Mecha and I both thank you for the quick fix, our server wouldn't be the same without all the rusty hatches.

**Comment by Ordinastie** [comment]
You're welcome :)

**Comment by Hastling** [comment]
Just a side note, the placement of the hatch is still odd. What I mean to say by that is if one places the hatch anywhere in a 2x2 hole other than the top edge of the right hand block that the player is facing the hatch will not place at all and will vanish from both the world and the players inv. I can upload pictures to better describe this if you need.

**Comment by Ordinastie** [comment]
Oh, that's a different bug I didn't notice, it shouldn't remove the Item when it fails placing. I'll fix that soon :)

**Comment by Hastling** [comment]
Thanks once again I'll watch curseforge and looking forward to the fix.
