### ISSUE TITLE
Missing texture for Wooden and Iron doors

### ISSUE THREAD

**Issue by ghost** [Ordinastie/MalisisDoors#94]
Minecraft 1.10.2 and using latest Malisis Core 4.1.1 and Malisis Doors 5.0.2. The texture icon for the Wooden and Iron doors is missing in JEI/WAILA/Creative tabs.
When placed in the world, they render normally though.

**Comment by ghost** [comment]
Screenshots to demonstrate better.
[B:config.modifyVanillaDoors=false](http://i.imgur.com/YtVaapg.png)
![2016-08-04_23 55 28](https://cloud.githubusercontent.com/assets/4369462/17421219/01e01580-5aa0-11e6-858e-75bbea858101.png)
[B:config.modifyVanillaDoors=true](http://i.imgur.com/U3Gc3iG.png)
![2016-08-04_23 58 13](https://cloud.githubusercontent.com/assets/4369462/17421229/20fa88ec-5aa0-11e6-8cf5-f0e655ea83b8.png)

**Comment by Ordinastie** [comment]
Please try with only MalisisDoors installed. Your screen shows many more doors than the ones I add, so I'm pretty sure that mod is what breaks it.

**Comment by ghost** [comment]
I stand corrected sir. It was the basemetals mod messing your icon textures.

**Comment by psychofad** [comment]
@Tickbuz 

have you found a way around this issue besides removing basemetals?

**Comment by ghost** [comment]
Not really. Basemetals redefines the door textures which I guess is the source of the problem. [https://github.com/cyanobacterium/BaseMetals/tree/master/src/main/resources/assets/minecraft/models/item](url)

**Comment by jriwanek** [comment]
I am working on the problem, Chances are I'll break out the changed things to a seperate resource pack.
