### ISSUE TITLE
3D Resource Packs-1.10.2

### ISSUE THREAD

**Issue by WenXin20** [Ordinastie/MalisisDoors#95]
3d resource packs that makes trapdoors or doors 3d don't seem to work. RP I used: [Default 3D](http://www.planetminecraft.com/texture_pack/default-3d-models-by-sibsib92-v01)

**Comment by Ordinastie** [comment]
Yes, the blocks in my mods are not rendered using JSON models, so you can't override them with resource packs. Sorry.

**Comment by WenXin20** [comment]
Ok, that's fine
