### ISSUE TITLE
Large amounts of fence gates kill FPS.

### ISSUE THREAD

**Issue by Claycorp** [Ordinastie/MalisisDoors#97]
On the server I manage someone had ~600 fence gates in their build and after we added the mod nobody could get near the build without dropping to 0-10 fps. When it was around 100FPS before. Once the gates were taken out the FPS returned to normal.

The gates were sitting idle so there shouldn't have been such a bad FPS drop. I am unsure if this will happen with any other blocks.

**Comment by Ordinastie** [comment]
Well, it is expected. To allow fence gates to be animated, I do have to render them every frame, contrary to block, that are rendered only when the chunk they're in are rerendered.
So yes, if you want to have animated doors, you can't really use them as random decorative blocks.

**Comment by Claycorp** [comment]
Alright. Thanks for the info.
