### ISSUE TITLE
1.10.2 (malisisdoors-1.9.4-5.0.3)

### ISSUE THREAD

**Issue by sosenka1** [Ordinastie/MalisisDoors#98]
When unloading the chunk is
![2016-08-27_00 26 01](https://cloud.githubusercontent.com/assets/21124829/18019424/ace599dc-6be4-11e6-9db7-f044e392943e.png)

**Comment by Ordinastie** [comment]
Does it happen reliably?

**Comment by sosenka1** [comment]
Yes, every time you come out of the chunk, rejoining fails

**Comment by Ordinastie** [comment]
Fixed in 1.10.2-5.1.4.
